// Code generated by protoc-gen-go.
// source: AccessControl.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

*
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

It is generated from these files:
	AccessControl.proto
	Admin.proto
	Backup.proto
	Cell.proto
	Client.proto
	ClusterId.proto
	ClusterStatus.proto
	Comparator.proto
	Encryption.proto
	ErrorHandling.proto
	Filter.proto
	FS.proto
	HBase.proto
	HFile.proto
	LoadBalancer.proto
	LockService.proto
	MapReduce.proto
	MasterProcedure.proto
	Master.proto
	Procedure.proto
	Quota.proto
	RegionServerStatus.proto
	Replication.proto
	RPC.proto
	Snapshot.proto
	Tracing.proto
	WAL.proto
	ZooKeeper.proto

It has these top-level messages:
	Permission
	TablePermission
	NamespacePermission
	GlobalPermission
	UserPermission
	UsersAndPermissions
	GrantRequest
	GrantResponse
	RevokeRequest
	RevokeResponse
	GetUserPermissionsRequest
	GetUserPermissionsResponse
	CheckPermissionsRequest
	CheckPermissionsResponse
	GetRegionInfoRequest
	GetRegionInfoResponse
	GetStoreFileRequest
	GetStoreFileResponse
	GetOnlineRegionRequest
	GetOnlineRegionResponse
	OpenRegionRequest
	OpenRegionResponse
	WarmupRegionRequest
	WarmupRegionResponse
	CloseRegionRequest
	CloseRegionResponse
	FlushRegionRequest
	FlushRegionResponse
	SplitRegionRequest
	SplitRegionResponse
	CompactRegionRequest
	CompactRegionResponse
	UpdateFavoredNodesRequest
	UpdateFavoredNodesResponse
	WALEntry
	ReplicateWALEntryRequest
	ReplicateWALEntryResponse
	RollWALWriterRequest
	RollWALWriterResponse
	StopServerRequest
	StopServerResponse
	GetServerInfoRequest
	ServerInfo
	GetServerInfoResponse
	UpdateConfigurationRequest
	UpdateConfigurationResponse
	GetRegionLoadRequest
	GetRegionLoadResponse
	ClearCompactionQueuesRequest
	ClearCompactionQueuesResponse
	ExecuteProceduresRequest
	ExecuteProceduresResponse
	MergeRegionsRequest
	MergeRegionsResponse
	ServerTimestamp
	TableServerTimestamp
	BackupImage
	BackupTableInfo
	BackupInfo
	Cell
	KeyValue
	Authorizations
	CellVisibility
	Column
	Get
	Result
	GetRequest
	GetResponse
	Condition
	MutationProto
	MutateRequest
	MutateResponse
	Scan
	ScanRequest
	Cursor
	ScanResponse
	BulkLoadHFileRequest
	BulkLoadHFileResponse
	DelegationToken
	PrepareBulkLoadRequest
	PrepareBulkLoadResponse
	CleanupBulkLoadRequest
	CleanupBulkLoadResponse
	CoprocessorServiceCall
	CoprocessorServiceResult
	CoprocessorServiceRequest
	CoprocessorServiceResponse
	Action
	RegionAction
	RegionLoadStats
	MultiRegionLoadStats
	ResultOrException
	RegionActionResult
	MultiRequest
	MultiResponse
	ClusterId
	RegionState
	RegionInTransition
	StoreSequenceId
	RegionStoreSequenceIds
	RegionLoad
	ReplicationLoadSink
	ReplicationLoadSource
	ServerLoad
	LiveServerInfo
	ClusterStatus
	Comparator
	ByteArrayComparable
	BinaryComparator
	LongComparator
	BinaryPrefixComparator
	BitComparator
	NullComparator
	RegexStringComparator
	SubstringComparator
	WrappedKey
	StackTraceElementMessage
	GenericExceptionMessage
	ForeignExceptionMessage
	Filter
	ColumnCountGetFilter
	ColumnPaginationFilter
	ColumnPrefixFilter
	ColumnRangeFilter
	CompareFilter
	DependentColumnFilter
	FamilyFilter
	FilterList
	FilterWrapper
	FirstKeyOnlyFilter
	FirstKeyValueMatchingQualifiersFilter
	FuzzyRowFilter
	InclusiveStopFilter
	KeyOnlyFilter
	MultipleColumnPrefixFilter
	PageFilter
	PrefixFilter
	QualifierFilter
	RandomRowFilter
	RowFilter
	SingleColumnValueExcludeFilter
	SingleColumnValueFilter
	SkipFilter
	TimestampsFilter
	ValueFilter
	WhileMatchFilter
	FilterAllFilter
	RowRange
	MultiRowRangeFilter
	HBaseVersionFileContent
	Reference
	TableName
	TableSchema
	TableState
	ColumnFamilySchema
	RegionInfo
	FavoredNodes
	RegionSpecifier
	TimeRange
	ColumnFamilyTimeRange
	ServerName
	Coprocessor
	NameStringPair
	NameBytesPair
	BytesBytesPair
	NameInt64Pair
	ProcedureDescription
	EmptyMsg
	LongMsg
	DoubleMsg
	BigDecimalMsg
	UUID
	NamespaceDescriptor
	VersionInfo
	RegionServerInfo
	FileInfoProto
	FileTrailerProto
	LoadBalancerState
	LockRequest
	LockResponse
	LockHeartbeatRequest
	LockHeartbeatResponse
	LockProcedureData
	WaitingProcedure
	LockInfo
	ScanMetrics
	TableSnapshotRegionSplit
	CreateTableStateData
	ModifyTableStateData
	TruncateTableStateData
	DeleteTableStateData
	CreateNamespaceStateData
	ModifyNamespaceStateData
	DeleteNamespaceStateData
	AddColumnFamilyStateData
	ModifyColumnFamilyStateData
	DeleteColumnFamilyStateData
	EnableTableStateData
	DisableTableStateData
	RestoreParentToChildRegionsPair
	CloneSnapshotStateData
	RestoreSnapshotStateData
	DispatchMergingRegionsStateData
	SplitTableRegionStateData
	MergeTableRegionsStateData
	ServerCrashStateData
	AssignRegionStateData
	UnassignRegionStateData
	MoveRegionStateData
	GCRegionStateData
	GCMergedRegionsStateData
	AddColumnRequest
	AddColumnResponse
	DeleteColumnRequest
	DeleteColumnResponse
	ModifyColumnRequest
	ModifyColumnResponse
	MoveRegionRequest
	MoveRegionResponse
	DispatchMergingRegionsRequest
	DispatchMergingRegionsResponse
	MergeTableRegionsRequest
	MergeTableRegionsResponse
	AssignRegionRequest
	AssignRegionResponse
	UnassignRegionRequest
	UnassignRegionResponse
	OfflineRegionRequest
	OfflineRegionResponse
	SplitTableRegionRequest
	SplitTableRegionResponse
	CreateTableRequest
	CreateTableResponse
	DeleteTableRequest
	DeleteTableResponse
	TruncateTableRequest
	TruncateTableResponse
	EnableTableRequest
	EnableTableResponse
	DisableTableRequest
	DisableTableResponse
	ModifyTableRequest
	ModifyTableResponse
	CreateNamespaceRequest
	CreateNamespaceResponse
	DeleteNamespaceRequest
	DeleteNamespaceResponse
	ModifyNamespaceRequest
	ModifyNamespaceResponse
	GetNamespaceDescriptorRequest
	GetNamespaceDescriptorResponse
	ListNamespaceDescriptorsRequest
	ListNamespaceDescriptorsResponse
	ListTableDescriptorsByNamespaceRequest
	ListTableDescriptorsByNamespaceResponse
	ListTableNamesByNamespaceRequest
	ListTableNamesByNamespaceResponse
	ShutdownRequest
	ShutdownResponse
	StopMasterRequest
	StopMasterResponse
	IsInMaintenanceModeRequest
	IsInMaintenanceModeResponse
	BalanceRequest
	BalanceResponse
	SetBalancerRunningRequest
	SetBalancerRunningResponse
	IsBalancerEnabledRequest
	IsBalancerEnabledResponse
	SetSplitOrMergeEnabledRequest
	SetSplitOrMergeEnabledResponse
	IsSplitOrMergeEnabledRequest
	IsSplitOrMergeEnabledResponse
	NormalizeRequest
	NormalizeResponse
	SetNormalizerRunningRequest
	SetNormalizerRunningResponse
	IsNormalizerEnabledRequest
	IsNormalizerEnabledResponse
	RunCatalogScanRequest
	RunCatalogScanResponse
	EnableCatalogJanitorRequest
	EnableCatalogJanitorResponse
	IsCatalogJanitorEnabledRequest
	IsCatalogJanitorEnabledResponse
	RunCleanerChoreRequest
	RunCleanerChoreResponse
	SetCleanerChoreRunningRequest
	SetCleanerChoreRunningResponse
	IsCleanerChoreEnabledRequest
	IsCleanerChoreEnabledResponse
	SnapshotRequest
	SnapshotResponse
	GetCompletedSnapshotsRequest
	GetCompletedSnapshotsResponse
	DeleteSnapshotRequest
	DeleteSnapshotResponse
	RestoreSnapshotRequest
	RestoreSnapshotResponse
	IsSnapshotDoneRequest
	IsSnapshotDoneResponse
	IsRestoreSnapshotDoneRequest
	IsRestoreSnapshotDoneResponse
	GetSchemaAlterStatusRequest
	GetSchemaAlterStatusResponse
	GetTableDescriptorsRequest
	GetTableDescriptorsResponse
	GetTableNamesRequest
	GetTableNamesResponse
	GetTableStateRequest
	GetTableStateResponse
	GetClusterStatusRequest
	GetClusterStatusResponse
	IsMasterRunningRequest
	IsMasterRunningResponse
	ExecProcedureRequest
	ExecProcedureResponse
	IsProcedureDoneRequest
	IsProcedureDoneResponse
	GetProcedureResultRequest
	GetProcedureResultResponse
	AbortProcedureRequest
	AbortProcedureResponse
	ListProceduresRequest
	ListProceduresResponse
	ListLocksRequest
	ListLocksResponse
	SetQuotaRequest
	SetQuotaResponse
	MajorCompactionTimestampRequest
	MajorCompactionTimestampForRegionRequest
	MajorCompactionTimestampResponse
	SecurityCapabilitiesRequest
	SecurityCapabilitiesResponse
	ListDrainingRegionServersRequest
	ListDrainingRegionServersResponse
	DrainRegionServersRequest
	DrainRegionServersResponse
	RemoveDrainFromRegionServersRequest
	RemoveDrainFromRegionServersResponse
	Procedure
	SequentialProcedureData
	StateMachineProcedureData
	ProcedureWALHeader
	ProcedureWALTrailer
	ProcedureStoreTracker
	ProcedureWALEntry
	TimedQuota
	Throttle
	ThrottleRequest
	Quotas
	QuotaUsage
	SpaceQuota
	SpaceLimitRequest
	SpaceQuotaStatus
	SpaceQuotaSnapshot
	GetSpaceQuotaRegionSizesRequest
	GetSpaceQuotaRegionSizesResponse
	GetSpaceQuotaSnapshotsRequest
	GetSpaceQuotaSnapshotsResponse
	GetQuotaStatesRequest
	GetQuotaStatesResponse
	RegionServerStartupRequest
	RegionServerStartupResponse
	RegionServerReportRequest
	RegionServerReportResponse
	ReportRSFatalErrorRequest
	ReportRSFatalErrorResponse
	GetLastFlushedSequenceIdRequest
	GetLastFlushedSequenceIdResponse
	RegionStateTransition
	ReportRegionStateTransitionRequest
	ReportRegionStateTransitionResponse
	RegionSpaceUse
	RegionSpaceUseReportRequest
	RegionSpaceUseReportResponse
	TableCF
	ReplicationPeer
	ReplicationState
	ReplicationPeerDescription
	ReplicationHLogPosition
	AddReplicationPeerRequest
	AddReplicationPeerResponse
	RemoveReplicationPeerRequest
	RemoveReplicationPeerResponse
	EnableReplicationPeerRequest
	EnableReplicationPeerResponse
	DisableReplicationPeerRequest
	DisableReplicationPeerResponse
	GetReplicationPeerConfigRequest
	GetReplicationPeerConfigResponse
	UpdateReplicationPeerConfigRequest
	UpdateReplicationPeerConfigResponse
	ListReplicationPeersRequest
	ListReplicationPeersResponse
	UserInformation
	ConnectionHeader
	ConnectionHeaderResponse
	CellBlockMeta
	ExceptionResponse
	CryptoCipherMeta
	RequestHeader
	ResponseHeader
	SnapshotDescription
	SnapshotFileInfo
	SnapshotRegionManifest
	SnapshotDataManifest
	RPCTInfo
	WALHeader
	WALKey
	FamilyScope
	CompactionDescriptor
	FlushDescriptor
	StoreDescriptor
	BulkLoadDescriptor
	RegionEventDescriptor
	WALTrailer
	MetaRegionServer
	Master
	ClusterUp
	SplitLogTask
	DeprecatedTableState
	SwitchState
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Permission_Action int32

const (
	Permission_READ   Permission_Action = 0
	Permission_WRITE  Permission_Action = 1
	Permission_EXEC   Permission_Action = 2
	Permission_CREATE Permission_Action = 3
	Permission_ADMIN  Permission_Action = 4
)

var Permission_Action_name = map[int32]string{
	0: "READ",
	1: "WRITE",
	2: "EXEC",
	3: "CREATE",
	4: "ADMIN",
}
var Permission_Action_value = map[string]int32{
	"READ":   0,
	"WRITE":  1,
	"EXEC":   2,
	"CREATE": 3,
	"ADMIN":  4,
}

func (x Permission_Action) Enum() *Permission_Action {
	p := new(Permission_Action)
	*p = x
	return p
}
func (x Permission_Action) String() string {
	return proto.EnumName(Permission_Action_name, int32(x))
}
func (x *Permission_Action) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Permission_Action_value, data, "Permission_Action")
	if err != nil {
		return err
	}
	*x = Permission_Action(value)
	return nil
}
func (Permission_Action) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Permission_Type int32

const (
	Permission_Global    Permission_Type = 1
	Permission_Namespace Permission_Type = 2
	Permission_Table     Permission_Type = 3
)

var Permission_Type_name = map[int32]string{
	1: "Global",
	2: "Namespace",
	3: "Table",
}
var Permission_Type_value = map[string]int32{
	"Global":    1,
	"Namespace": 2,
	"Table":     3,
}

func (x Permission_Type) Enum() *Permission_Type {
	p := new(Permission_Type)
	*p = x
	return p
}
func (x Permission_Type) String() string {
	return proto.EnumName(Permission_Type_name, int32(x))
}
func (x *Permission_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Permission_Type_value, data, "Permission_Type")
	if err != nil {
		return err
	}
	*x = Permission_Type(value)
	return nil
}
func (Permission_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

type Permission struct {
	Type                *Permission_Type     `protobuf:"varint,1,req,name=type,enum=pb.Permission_Type" json:"type,omitempty"`
	GlobalPermission    *GlobalPermission    `protobuf:"bytes,2,opt,name=global_permission,json=globalPermission" json:"global_permission,omitempty"`
	NamespacePermission *NamespacePermission `protobuf:"bytes,3,opt,name=namespace_permission,json=namespacePermission" json:"namespace_permission,omitempty"`
	TablePermission     *TablePermission     `protobuf:"bytes,4,opt,name=table_permission,json=tablePermission" json:"table_permission,omitempty"`
	XXX_unrecognized    []byte               `json:"-"`
}

func (m *Permission) Reset()                    { *m = Permission{} }
func (m *Permission) String() string            { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()               {}
func (*Permission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Permission) GetType() Permission_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Permission_Global
}

func (m *Permission) GetGlobalPermission() *GlobalPermission {
	if m != nil {
		return m.GlobalPermission
	}
	return nil
}

func (m *Permission) GetNamespacePermission() *NamespacePermission {
	if m != nil {
		return m.NamespacePermission
	}
	return nil
}

func (m *Permission) GetTablePermission() *TablePermission {
	if m != nil {
		return m.TablePermission
	}
	return nil
}

type TablePermission struct {
	TableName        *TableName          `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Family           []byte              `protobuf:"bytes,2,opt,name=family" json:"family,omitempty"`
	Qualifier        []byte              `protobuf:"bytes,3,opt,name=qualifier" json:"qualifier,omitempty"`
	Action           []Permission_Action `protobuf:"varint,4,rep,name=action,enum=pb.Permission_Action" json:"action,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *TablePermission) Reset()                    { *m = TablePermission{} }
func (m *TablePermission) String() string            { return proto.CompactTextString(m) }
func (*TablePermission) ProtoMessage()               {}
func (*TablePermission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TablePermission) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *TablePermission) GetFamily() []byte {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *TablePermission) GetQualifier() []byte {
	if m != nil {
		return m.Qualifier
	}
	return nil
}

func (m *TablePermission) GetAction() []Permission_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type NamespacePermission struct {
	NamespaceName    []byte              `protobuf:"bytes,1,opt,name=namespace_name,json=namespaceName" json:"namespace_name,omitempty"`
	Action           []Permission_Action `protobuf:"varint,2,rep,name=action,enum=pb.Permission_Action" json:"action,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *NamespacePermission) Reset()                    { *m = NamespacePermission{} }
func (m *NamespacePermission) String() string            { return proto.CompactTextString(m) }
func (*NamespacePermission) ProtoMessage()               {}
func (*NamespacePermission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NamespacePermission) GetNamespaceName() []byte {
	if m != nil {
		return m.NamespaceName
	}
	return nil
}

func (m *NamespacePermission) GetAction() []Permission_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type GlobalPermission struct {
	Action           []Permission_Action `protobuf:"varint,1,rep,name=action,enum=pb.Permission_Action" json:"action,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GlobalPermission) Reset()                    { *m = GlobalPermission{} }
func (m *GlobalPermission) String() string            { return proto.CompactTextString(m) }
func (*GlobalPermission) ProtoMessage()               {}
func (*GlobalPermission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GlobalPermission) GetAction() []Permission_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

type UserPermission struct {
	User             []byte      `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Permission       *Permission `protobuf:"bytes,3,req,name=permission" json:"permission,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *UserPermission) Reset()                    { *m = UserPermission{} }
func (m *UserPermission) String() string            { return proto.CompactTextString(m) }
func (*UserPermission) ProtoMessage()               {}
func (*UserPermission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UserPermission) GetUser() []byte {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserPermission) GetPermission() *Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

// *
// Content of the /hbase/acl/<table or namespace> znode.
type UsersAndPermissions struct {
	UserPermissions  []*UsersAndPermissions_UserPermissions `protobuf:"bytes,1,rep,name=user_permissions,json=userPermissions" json:"user_permissions,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *UsersAndPermissions) Reset()                    { *m = UsersAndPermissions{} }
func (m *UsersAndPermissions) String() string            { return proto.CompactTextString(m) }
func (*UsersAndPermissions) ProtoMessage()               {}
func (*UsersAndPermissions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UsersAndPermissions) GetUserPermissions() []*UsersAndPermissions_UserPermissions {
	if m != nil {
		return m.UserPermissions
	}
	return nil
}

type UsersAndPermissions_UserPermissions struct {
	User             []byte        `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	Permissions      []*Permission `protobuf:"bytes,2,rep,name=permissions" json:"permissions,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *UsersAndPermissions_UserPermissions) Reset()         { *m = UsersAndPermissions_UserPermissions{} }
func (m *UsersAndPermissions_UserPermissions) String() string { return proto.CompactTextString(m) }
func (*UsersAndPermissions_UserPermissions) ProtoMessage()    {}
func (*UsersAndPermissions_UserPermissions) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *UsersAndPermissions_UserPermissions) GetUser() []byte {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UsersAndPermissions_UserPermissions) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type GrantRequest struct {
	UserPermission           *UserPermission `protobuf:"bytes,1,req,name=user_permission,json=userPermission" json:"user_permission,omitempty"`
	MergeExistingPermissions *bool           `protobuf:"varint,2,opt,name=merge_existing_permissions,json=mergeExistingPermissions,def=0" json:"merge_existing_permissions,omitempty"`
	XXX_unrecognized         []byte          `json:"-"`
}

func (m *GrantRequest) Reset()                    { *m = GrantRequest{} }
func (m *GrantRequest) String() string            { return proto.CompactTextString(m) }
func (*GrantRequest) ProtoMessage()               {}
func (*GrantRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

const Default_GrantRequest_MergeExistingPermissions bool = false

func (m *GrantRequest) GetUserPermission() *UserPermission {
	if m != nil {
		return m.UserPermission
	}
	return nil
}

func (m *GrantRequest) GetMergeExistingPermissions() bool {
	if m != nil && m.MergeExistingPermissions != nil {
		return *m.MergeExistingPermissions
	}
	return Default_GrantRequest_MergeExistingPermissions
}

type GrantResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GrantResponse) Reset()                    { *m = GrantResponse{} }
func (m *GrantResponse) String() string            { return proto.CompactTextString(m) }
func (*GrantResponse) ProtoMessage()               {}
func (*GrantResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RevokeRequest struct {
	UserPermission   *UserPermission `protobuf:"bytes,1,req,name=user_permission,json=userPermission" json:"user_permission,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RevokeRequest) Reset()                    { *m = RevokeRequest{} }
func (m *RevokeRequest) String() string            { return proto.CompactTextString(m) }
func (*RevokeRequest) ProtoMessage()               {}
func (*RevokeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RevokeRequest) GetUserPermission() *UserPermission {
	if m != nil {
		return m.UserPermission
	}
	return nil
}

type RevokeResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RevokeResponse) Reset()                    { *m = RevokeResponse{} }
func (m *RevokeResponse) String() string            { return proto.CompactTextString(m) }
func (*RevokeResponse) ProtoMessage()               {}
func (*RevokeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GetUserPermissionsRequest struct {
	Type             *Permission_Type `protobuf:"varint,1,opt,name=type,enum=pb.Permission_Type" json:"type,omitempty"`
	TableName        *TableName       `protobuf:"bytes,2,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	NamespaceName    []byte           `protobuf:"bytes,3,opt,name=namespace_name,json=namespaceName" json:"namespace_name,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GetUserPermissionsRequest) Reset()                    { *m = GetUserPermissionsRequest{} }
func (m *GetUserPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserPermissionsRequest) ProtoMessage()               {}
func (*GetUserPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetUserPermissionsRequest) GetType() Permission_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Permission_Global
}

func (m *GetUserPermissionsRequest) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *GetUserPermissionsRequest) GetNamespaceName() []byte {
	if m != nil {
		return m.NamespaceName
	}
	return nil
}

type GetUserPermissionsResponse struct {
	UserPermission   []*UserPermission `protobuf:"bytes,1,rep,name=user_permission,json=userPermission" json:"user_permission,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *GetUserPermissionsResponse) Reset()                    { *m = GetUserPermissionsResponse{} }
func (m *GetUserPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserPermissionsResponse) ProtoMessage()               {}
func (*GetUserPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetUserPermissionsResponse) GetUserPermission() []*UserPermission {
	if m != nil {
		return m.UserPermission
	}
	return nil
}

type CheckPermissionsRequest struct {
	Permission       []*Permission `protobuf:"bytes,1,rep,name=permission" json:"permission,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *CheckPermissionsRequest) Reset()                    { *m = CheckPermissionsRequest{} }
func (m *CheckPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckPermissionsRequest) ProtoMessage()               {}
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CheckPermissionsRequest) GetPermission() []*Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

type CheckPermissionsResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CheckPermissionsResponse) Reset()                    { *m = CheckPermissionsResponse{} }
func (m *CheckPermissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckPermissionsResponse) ProtoMessage()               {}
func (*CheckPermissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto.RegisterType((*Permission)(nil), "pb.Permission")
	proto.RegisterType((*TablePermission)(nil), "pb.TablePermission")
	proto.RegisterType((*NamespacePermission)(nil), "pb.NamespacePermission")
	proto.RegisterType((*GlobalPermission)(nil), "pb.GlobalPermission")
	proto.RegisterType((*UserPermission)(nil), "pb.UserPermission")
	proto.RegisterType((*UsersAndPermissions)(nil), "pb.UsersAndPermissions")
	proto.RegisterType((*UsersAndPermissions_UserPermissions)(nil), "pb.UsersAndPermissions.UserPermissions")
	proto.RegisterType((*GrantRequest)(nil), "pb.GrantRequest")
	proto.RegisterType((*GrantResponse)(nil), "pb.GrantResponse")
	proto.RegisterType((*RevokeRequest)(nil), "pb.RevokeRequest")
	proto.RegisterType((*RevokeResponse)(nil), "pb.RevokeResponse")
	proto.RegisterType((*GetUserPermissionsRequest)(nil), "pb.GetUserPermissionsRequest")
	proto.RegisterType((*GetUserPermissionsResponse)(nil), "pb.GetUserPermissionsResponse")
	proto.RegisterType((*CheckPermissionsRequest)(nil), "pb.CheckPermissionsRequest")
	proto.RegisterType((*CheckPermissionsResponse)(nil), "pb.CheckPermissionsResponse")
	proto.RegisterEnum("pb.Permission_Action", Permission_Action_name, Permission_Action_value)
	proto.RegisterEnum("pb.Permission_Type", Permission_Type_name, Permission_Type_value)
}

var fileDescriptor0 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x66, 0x9d, 0x34, 0x6a, 0x26, 0x7f, 0xee, 0xa6, 0xd0, 0x60, 0x0a, 0xaa, 0x2c, 0xa1, 0xf6,
	0x50, 0x0c, 0xe4, 0x08, 0x52, 0xa5, 0x34, 0x8d, 0xda, 0x22, 0x5a, 0x55, 0xdb, 0xa0, 0xc2, 0xa9,
	0x72, 0x92, 0x4d, 0x62, 0x35, 0xb1, 0x5d, 0xaf, 0x53, 0xd1, 0x37, 0xe0, 0xc8, 0xb5, 0x37, 0x0e,
	0x3c, 0x09, 0x8f, 0xc4, 0x13, 0xe0, 0x5d, 0x3b, 0xf1, 0xda, 0x71, 0xa1, 0x07, 0x6e, 0xde, 0xf9,
	0xf9, 0xf6, 0x9b, 0x6f, 0x66, 0xbc, 0x50, 0x6f, 0xf5, 0xfb, 0x94, 0xb1, 0xb6, 0x63, 0xfb, 0x9e,
	0x33, 0x31, 0x5c, 0xcf, 0xf1, 0x1d, 0xac, 0xb8, 0x3d, 0xad, 0x74, 0xb4, 0x6f, 0x32, 0x1a, 0x1a,
	0xf4, 0xdf, 0x0a, 0xc0, 0x19, 0xf5, 0xa6, 0x16, 0x63, 0x96, 0x63, 0xe3, 0x6d, 0xc8, 0xfb, 0xb7,
	0x2e, 0x6d, 0xa0, 0x2d, 0x65, 0xa7, 0xda, 0xac, 0x1b, 0x6e, 0xcf, 0x88, 0xbd, 0x46, 0x37, 0x70,
	0x11, 0x11, 0x80, 0x5b, 0xb0, 0x36, 0x9a, 0x38, 0x3d, 0x73, 0x72, 0xe9, 0x2e, 0xfc, 0x0d, 0x65,
	0x0b, 0xed, 0x94, 0x9a, 0xeb, 0x3c, 0xeb, 0x50, 0x38, 0xe3, 0x5c, 0xa2, 0x8e, 0x52, 0x16, 0xfc,
	0x01, 0xd6, 0x6d, 0x73, 0x4a, 0x99, 0x6b, 0xf6, 0xa9, 0x8c, 0x92, 0x13, 0x28, 0x1b, 0x1c, 0xe5,
	0x74, 0xee, 0x97, 0x80, 0xea, 0xf6, 0xb2, 0x11, 0xef, 0x81, 0xea, 0x9b, 0xbd, 0x49, 0x02, 0x27,
	0x2f, 0x70, 0x44, 0x0d, 0x5d, 0xee, 0x93, 0x30, 0x6a, 0x7e, 0xd2, 0xa0, 0xef, 0x41, 0xa1, 0xd5,
	0xf7, 0x39, 0xd2, 0x2a, 0xe4, 0x49, 0xa7, 0x75, 0xa0, 0x3e, 0xc2, 0x45, 0x58, 0xb9, 0x20, 0xc7,
	0xdd, 0x8e, 0x8a, 0xb8, 0xb1, 0xf3, 0xb9, 0xd3, 0x56, 0x15, 0x0c, 0x50, 0x68, 0x07, 0xfe, 0xc0,
	0x9a, 0xe3, 0x01, 0xad, 0x83, 0x93, 0xe3, 0x53, 0x35, 0xaf, 0xef, 0x42, 0x9e, 0x8b, 0xc3, 0xdd,
	0x61, 0xe5, 0x41, 0x52, 0x05, 0x8a, 0x0b, 0xfe, 0x41, 0x66, 0x10, 0x2d, 0x68, 0xa8, 0x39, 0xfd,
	0x27, 0x82, 0x5a, 0x8a, 0x12, 0xde, 0x05, 0x08, 0x2b, 0xe0, 0xe5, 0x05, 0xfa, 0x73, 0xee, 0x95,
	0x05, 0x77, 0x0e, 0x44, 0x8a, 0xfe, 0xfc, 0x13, 0x3f, 0x81, 0xc2, 0xd0, 0x9c, 0x5a, 0x93, 0x5b,
	0xa1, 0x79, 0x99, 0x44, 0x27, 0xbc, 0x09, 0xc5, 0xeb, 0x99, 0x39, 0xb1, 0x86, 0x16, 0xf5, 0x84,
	0x90, 0x65, 0x12, 0x1b, 0xf0, 0x2b, 0x28, 0x98, 0xa2, 0xca, 0x40, 0x9b, 0x5c, 0xd0, 0xdf, 0xc7,
	0xa9, 0xfe, 0x86, 0x12, 0x90, 0x28, 0x48, 0xbf, 0x82, 0x7a, 0x46, 0x03, 0xf0, 0x4b, 0xa8, 0xc6,
	0x7d, 0x5b, 0xb0, 0x2d, 0x93, 0xca, 0xc2, 0x2a, 0x28, 0xc6, 0x97, 0x29, 0x0f, 0xb9, 0xac, 0x05,
	0x6a, 0x7a, 0x66, 0x24, 0x08, 0xf4, 0x10, 0x88, 0x2e, 0x54, 0x3f, 0x31, 0xea, 0x49, 0x00, 0x18,
	0xf2, 0xb3, 0xc0, 0x22, 0xc6, 0xb9, 0x4c, 0xc4, 0x37, 0x36, 0x00, 0x12, 0xc3, 0xa6, 0x04, 0x42,
	0x57, 0x93, 0xc0, 0x44, 0x8a, 0xd0, 0x7f, 0x21, 0xa8, 0x73, 0x58, 0xd6, 0xb2, 0x07, 0x71, 0x08,
	0xc3, 0x04, 0x54, 0x8e, 0x27, 0x4d, 0x1c, 0x13, 0x34, 0x4b, 0xcd, 0x6d, 0x8e, 0x96, 0x91, 0x62,
	0x24, 0xd9, 0x31, 0x52, 0x9b, 0x25, 0x0d, 0xda, 0x05, 0xd4, 0x52, 0x31, 0x99, 0x25, 0xbc, 0x81,
	0x92, 0x7c, 0xab, 0x22, 0x6e, 0x4d, 0xd7, 0x20, 0x87, 0xe8, 0xdf, 0x11, 0x94, 0x0f, 0x3d, 0xd3,
	0xf6, 0x09, 0xbd, 0x9e, 0x51, 0xe6, 0xe3, 0xf7, 0x50, 0x4b, 0xb1, 0x17, 0x37, 0x94, 0x9a, 0x78,
	0x4e, 0x5e, 0x82, 0xaa, 0x26, 0x79, 0xe2, 0x36, 0x68, 0x53, 0xea, 0x8d, 0xe8, 0x25, 0xfd, 0x6a,
	0x31, 0xdf, 0xb2, 0x47, 0x97, 0x49, 0x3a, 0x68, 0x67, 0xf5, 0xdd, 0xca, 0xd0, 0x9c, 0x30, 0x4a,
	0x1a, 0x22, 0xb0, 0x13, 0xc5, 0x49, 0x85, 0xe9, 0x35, 0xa8, 0x44, 0x8c, 0x98, 0x1b, 0x9c, 0xa9,
	0xfe, 0x11, 0x2a, 0x84, 0xde, 0x38, 0x57, 0xf4, 0x7f, 0x70, 0xd4, 0x55, 0xa8, 0xce, 0xd1, 0x22,
	0xfc, 0x3b, 0x04, 0x4f, 0x0f, 0xa9, 0x9f, 0x6e, 0x42, 0x74, 0x59, 0xfc, 0xe7, 0x43, 0x7f, 0xff,
	0xf3, 0x25, 0x17, 0x55, 0xf9, 0xc7, 0xa2, 0x2e, 0x2f, 0x4b, 0x2e, 0x63, 0x59, 0xf4, 0x2f, 0xa0,
	0x65, 0x51, 0x0b, 0x99, 0x67, 0x0b, 0x91, 0x7b, 0xa0, 0x10, 0xc7, 0xb0, 0xd1, 0x1e, 0xd3, 0xfe,
	0x55, 0x46, 0xcd, 0xc9, 0x55, 0x40, 0x99, 0x63, 0x24, 0xaf, 0x82, 0x06, 0x8d, 0x65, 0xa8, 0x90,
	0x63, 0xf3, 0x4e, 0x81, 0xf5, 0xc4, 0x8b, 0x73, 0x4e, 0xbd, 0x1b, 0xab, 0xcf, 0xf5, 0x5a, 0x11,
	0x7d, 0xc6, 0xaa, 0x78, 0x17, 0xa4, 0x21, 0xd4, 0xd6, 0x24, 0x4b, 0x54, 0xea, 0x6b, 0x28, 0x84,
	0x6d, 0xc3, 0xc2, 0x99, 0x18, 0x08, 0x0d, 0xcb, 0xa6, 0x28, 0xe1, 0x1c, 0xf0, 0xb2, 0x72, 0xf8,
	0xb9, 0x40, 0xbe, 0xaf, 0xd9, 0xda, 0x8b, 0xfb, 0xdc, 0x11, 0xe8, 0x09, 0xa8, 0xe9, 0x42, 0xf1,
	0x33, 0x9e, 0x73, 0x8f, 0x92, 0xda, 0x66, 0xb6, 0x33, 0x84, 0xdb, 0x3f, 0x83, 0xb7, 0x8e, 0x37,
	0x32, 0xcc, 0xa0, 0xdd, 0x63, 0x6a, 0x8c, 0xcd, 0x81, 0xe3, 0xb8, 0xc6, 0xb8, 0xc7, 0x5f, 0x61,
	0x16, 0x9c, 0xe8, 0x20, 0x7c, 0x8c, 0x7b, 0xb3, 0xa1, 0x31, 0xa2, 0x36, 0xf5, 0x4c, 0x9f, 0x0e,
	0xf6, 0x93, 0xef, 0xf7, 0x19, 0x0f, 0x60, 0x47, 0xe8, 0x1b, 0x42, 0x3f, 0x10, 0xfa, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x6e, 0x4a, 0x93, 0x8d, 0xdd, 0x07, 0x00, 0x00,
}
