// Code generated by protoc-gen-go.
// source: Cell.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
// The type of the key in a Cell
type CellType int32

const (
	CellType_MINIMUM       CellType = 0
	CellType_PUT           CellType = 4
	CellType_DELETE        CellType = 8
	CellType_DELETE_COLUMN CellType = 12
	CellType_DELETE_FAMILY CellType = 14
	// MAXIMUM is used when searching; you look from maximum on down.
	CellType_MAXIMUM CellType = 255
)

var CellType_name = map[int32]string{
	0:   "MINIMUM",
	4:   "PUT",
	8:   "DELETE",
	12:  "DELETE_COLUMN",
	14:  "DELETE_FAMILY",
	255: "MAXIMUM",
}
var CellType_value = map[string]int32{
	"MINIMUM":       0,
	"PUT":           4,
	"DELETE":        8,
	"DELETE_COLUMN": 12,
	"DELETE_FAMILY": 14,
	"MAXIMUM":       255,
}

func (x CellType) Enum() *CellType {
	p := new(CellType)
	*p = x
	return p
}
func (x CellType) String() string {
	return proto.EnumName(CellType_name, int32(x))
}
func (x *CellType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CellType_value, data, "CellType")
	if err != nil {
		return err
	}
	*x = CellType(value)
	return nil
}
func (CellType) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

// *
// Protocol buffer version of Cell.
type Cell struct {
	Row              []byte    `protobuf:"bytes,1,opt,name=row" json:"row,omitempty"`
	Family           []byte    `protobuf:"bytes,2,opt,name=family" json:"family,omitempty"`
	Qualifier        []byte    `protobuf:"bytes,3,opt,name=qualifier" json:"qualifier,omitempty"`
	Timestamp        *uint64   `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	CellType         *CellType `protobuf:"varint,5,opt,name=cell_type,json=cellType,enum=pb.CellType" json:"cell_type,omitempty"`
	Value            []byte    `protobuf:"bytes,6,opt,name=value" json:"value,omitempty"`
	Tags             []byte    `protobuf:"bytes,7,opt,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Cell) Reset()                    { *m = Cell{} }
func (m *Cell) String() string            { return proto.CompactTextString(m) }
func (*Cell) ProtoMessage()               {}
func (*Cell) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Cell) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *Cell) GetFamily() []byte {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *Cell) GetQualifier() []byte {
	if m != nil {
		return m.Qualifier
	}
	return nil
}

func (m *Cell) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *Cell) GetCellType() CellType {
	if m != nil && m.CellType != nil {
		return *m.CellType
	}
	return CellType_MINIMUM
}

func (m *Cell) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Cell) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

// *
// Protocol buffer version of KeyValue.
// It doesn't have those transient parameters
type KeyValue struct {
	Row              []byte    `protobuf:"bytes,1,req,name=row" json:"row,omitempty"`
	Family           []byte    `protobuf:"bytes,2,req,name=family" json:"family,omitempty"`
	Qualifier        []byte    `protobuf:"bytes,3,req,name=qualifier" json:"qualifier,omitempty"`
	Timestamp        *uint64   `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	KeyType          *CellType `protobuf:"varint,5,opt,name=key_type,json=keyType,enum=pb.CellType" json:"key_type,omitempty"`
	Value            []byte    `protobuf:"bytes,6,opt,name=value" json:"value,omitempty"`
	Tags             []byte    `protobuf:"bytes,7,opt,name=tags" json:"tags,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *KeyValue) GetRow() []byte {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *KeyValue) GetFamily() []byte {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *KeyValue) GetQualifier() []byte {
	if m != nil {
		return m.Qualifier
	}
	return nil
}

func (m *KeyValue) GetTimestamp() uint64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *KeyValue) GetKeyType() CellType {
	if m != nil && m.KeyType != nil {
		return *m.KeyType
	}
	return CellType_MINIMUM
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *KeyValue) GetTags() []byte {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Cell)(nil), "pb.Cell")
	proto.RegisterType((*KeyValue)(nil), "pb.KeyValue")
	proto.RegisterEnum("pb.CellType", CellType_name, CellType_value)
}

var fileDescriptor3 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0xef, 0x94, 0x42, 0xcb, 0xb9, 0xbd, 0xa4, 0x77, 0x62, 0xcc, 0x2c, 0x5c, 0x18, 0x36,
	0xfe, 0x59, 0x4c, 0xa2, 0x6f, 0xc0, 0x3f, 0x23, 0x91, 0x22, 0x21, 0x60, 0x74, 0x85, 0x53, 0x38,
	0x40, 0x63, 0xb1, 0x63, 0x5b, 0x34, 0x7d, 0x1b, 0x5f, 0xc5, 0xf8, 0x60, 0x3a, 0x1d, 0x50, 0x5c,
	0xc8, 0x82, 0xdd, 0xf7, 0xfd, 0xbe, 0xf6, 0x9c, 0xf9, 0x92, 0x03, 0xd0, 0xc0, 0x30, 0xe4, 0x32,
	0x8e, 0xd2, 0x88, 0x1a, 0xd2, 0xaf, 0xbe, 0x11, 0x30, 0x73, 0x44, 0x5d, 0x28, 0xc4, 0xd1, 0x0b,
	0x23, 0x87, 0xe4, 0xd8, 0xe9, 0xe7, 0x92, 0xee, 0x43, 0x69, 0x2a, 0x16, 0x41, 0x98, 0x31, 0x43,
	0xc3, 0xb5, 0xa3, 0x07, 0x50, 0x7e, 0x5a, 0x8a, 0x30, 0x98, 0x06, 0x18, 0xb3, 0x82, 0x8e, 0x36,
	0x20, 0x4f, 0xd3, 0x60, 0x81, 0x49, 0x2a, 0x16, 0x92, 0x99, 0x2a, 0x35, 0xfb, 0x1b, 0x40, 0x4f,
	0xa0, 0x3c, 0x56, 0xdb, 0x46, 0x69, 0x26, 0x91, 0x15, 0x55, 0x5a, 0x39, 0x77, 0xb8, 0xf4, 0x79,
	0xfe, 0x84, 0x81, 0x62, 0x7d, 0x7b, 0xbc, 0x56, 0x74, 0x0f, 0x8a, 0xcf, 0x22, 0x5c, 0x22, 0x2b,
	0xe9, 0x15, 0x2b, 0x43, 0x29, 0x98, 0xa9, 0x98, 0x25, 0xcc, 0xd2, 0x50, 0xeb, 0xea, 0x3b, 0x01,
	0xfb, 0x0a, 0xb3, 0x1b, 0xfd, 0xc1, 0x77, 0x0f, 0xe3, 0xb7, 0x1e, 0xc6, 0xf6, 0x1e, 0xc6, 0x2e,
	0x3d, 0x8e, 0xc0, 0x7e, 0xc0, 0x6c, 0x7b, 0x0d, 0x4b, 0xa5, 0xbb, 0xb5, 0x38, 0xbd, 0x07, 0xfb,
	0xeb, 0x77, 0xfa, 0x17, 0x2c, 0xaf, 0xdd, 0x6d, 0x7b, 0x43, 0xcf, 0xfd, 0x43, 0x2d, 0x28, 0xf4,
	0x86, 0x03, 0xd7, 0xa4, 0x00, 0xa5, 0x66, 0xab, 0xd3, 0x1a, 0xb4, 0x5c, 0x9b, 0xfe, 0x87, 0x7f,
	0x2b, 0x3d, 0x6a, 0x5c, 0x77, 0x86, 0x5e, 0xd7, 0x75, 0x7e, 0xa0, 0x8b, 0x9a, 0xd7, 0xee, 0xdc,
	0xb9, 0x15, 0xea, 0xa8, 0x39, 0xb5, 0x5b, 0x3d, 0xe7, 0x83, 0xd4, 0x9b, 0x70, 0x16, 0xc5, 0x33,
	0x2e, 0xa4, 0x18, 0xcf, 0x91, 0xcf, 0xc5, 0x24, 0x8a, 0x24, 0x9f, 0xfb, 0x22, 0x41, 0x9e, 0x28,
	0x87, 0x93, 0xd5, 0x5d, 0xf8, 0xcb, 0x29, 0x9f, 0xe1, 0x23, 0xc6, 0x22, 0xc5, 0x49, 0x5d, 0x1f,
	0x4c, 0x2f, 0xe7, 0xc9, 0x25, 0x79, 0x25, 0xe4, 0x33, 0x00, 0x00, 0xff, 0xff, 0x16, 0xbc, 0x67,
	0x3e, 0x42, 0x02, 0x00, 0x00,
}
