// Code generated by protoc-gen-go.
// source: HBase.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Comparison operators
type CompareType int32

const (
	CompareType_LESS             CompareType = 0
	CompareType_LESS_OR_EQUAL    CompareType = 1
	CompareType_EQUAL            CompareType = 2
	CompareType_NOT_EQUAL        CompareType = 3
	CompareType_GREATER_OR_EQUAL CompareType = 4
	CompareType_GREATER          CompareType = 5
	CompareType_NO_OP            CompareType = 6
)

var CompareType_name = map[int32]string{
	0: "LESS",
	1: "LESS_OR_EQUAL",
	2: "EQUAL",
	3: "NOT_EQUAL",
	4: "GREATER_OR_EQUAL",
	5: "GREATER",
	6: "NO_OP",
}
var CompareType_value = map[string]int32{
	"LESS":             0,
	"LESS_OR_EQUAL":    1,
	"EQUAL":            2,
	"NOT_EQUAL":        3,
	"GREATER_OR_EQUAL": 4,
	"GREATER":          5,
	"NO_OP":            6,
}

func (x CompareType) Enum() *CompareType {
	p := new(CompareType)
	*p = x
	return p
}
func (x CompareType) String() string {
	return proto.EnumName(CompareType_name, int32(x))
}
func (x *CompareType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CompareType_value, data, "CompareType")
	if err != nil {
		return err
	}
	*x = CompareType(value)
	return nil
}
func (CompareType) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

type TimeUnit int32

const (
	TimeUnit_NANOSECONDS  TimeUnit = 1
	TimeUnit_MICROSECONDS TimeUnit = 2
	TimeUnit_MILLISECONDS TimeUnit = 3
	TimeUnit_SECONDS      TimeUnit = 4
	TimeUnit_MINUTES      TimeUnit = 5
	TimeUnit_HOURS        TimeUnit = 6
	TimeUnit_DAYS         TimeUnit = 7
)

var TimeUnit_name = map[int32]string{
	1: "NANOSECONDS",
	2: "MICROSECONDS",
	3: "MILLISECONDS",
	4: "SECONDS",
	5: "MINUTES",
	6: "HOURS",
	7: "DAYS",
}
var TimeUnit_value = map[string]int32{
	"NANOSECONDS":  1,
	"MICROSECONDS": 2,
	"MILLISECONDS": 3,
	"SECONDS":      4,
	"MINUTES":      5,
	"HOURS":        6,
	"DAYS":         7,
}

func (x TimeUnit) Enum() *TimeUnit {
	p := new(TimeUnit)
	*p = x
	return p
}
func (x TimeUnit) String() string {
	return proto.EnumName(TimeUnit_name, int32(x))
}
func (x *TimeUnit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TimeUnit_value, data, "TimeUnit")
	if err != nil {
		return err
	}
	*x = TimeUnit(value)
	return nil
}
func (TimeUnit) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

// Table's current state
type TableState_State int32

const (
	TableState_ENABLED   TableState_State = 0
	TableState_DISABLED  TableState_State = 1
	TableState_DISABLING TableState_State = 2
	TableState_ENABLING  TableState_State = 3
)

var TableState_State_name = map[int32]string{
	0: "ENABLED",
	1: "DISABLED",
	2: "DISABLING",
	3: "ENABLING",
}
var TableState_State_value = map[string]int32{
	"ENABLED":   0,
	"DISABLED":  1,
	"DISABLING": 2,
	"ENABLING":  3,
}

func (x TableState_State) Enum() *TableState_State {
	p := new(TableState_State)
	*p = x
	return p
}
func (x TableState_State) String() string {
	return proto.EnumName(TableState_State_name, int32(x))
}
func (x *TableState_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TableState_State_value, data, "TableState_State")
	if err != nil {
		return err
	}
	*x = TableState_State(value)
	return nil
}
func (TableState_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{2, 0} }

type RegionSpecifier_RegionSpecifierType int32

const (
	// <tablename>,<startkey>,<regionId>.<encodedName>
	RegionSpecifier_REGION_NAME RegionSpecifier_RegionSpecifierType = 1
	// hash of <tablename>,<startkey>,<regionId>
	RegionSpecifier_ENCODED_REGION_NAME RegionSpecifier_RegionSpecifierType = 2
)

var RegionSpecifier_RegionSpecifierType_name = map[int32]string{
	1: "REGION_NAME",
	2: "ENCODED_REGION_NAME",
}
var RegionSpecifier_RegionSpecifierType_value = map[string]int32{
	"REGION_NAME":         1,
	"ENCODED_REGION_NAME": 2,
}

func (x RegionSpecifier_RegionSpecifierType) Enum() *RegionSpecifier_RegionSpecifierType {
	p := new(RegionSpecifier_RegionSpecifierType)
	*p = x
	return p
}
func (x RegionSpecifier_RegionSpecifierType) String() string {
	return proto.EnumName(RegionSpecifier_RegionSpecifierType_name, int32(x))
}
func (x *RegionSpecifier_RegionSpecifierType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegionSpecifier_RegionSpecifierType_value, data, "RegionSpecifier_RegionSpecifierType")
	if err != nil {
		return err
	}
	*x = RegionSpecifier_RegionSpecifierType(value)
	return nil
}
func (RegionSpecifier_RegionSpecifierType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor12, []int{6, 0}
}

// *
// Table Name
type TableName struct {
	Namespace        []byte `protobuf:"bytes,1,req,name=namespace" json:"namespace,omitempty"`
	Qualifier        []byte `protobuf:"bytes,2,req,name=qualifier" json:"qualifier,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TableName) Reset()                    { *m = TableName{} }
func (m *TableName) String() string            { return proto.CompactTextString(m) }
func (*TableName) ProtoMessage()               {}
func (*TableName) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *TableName) GetNamespace() []byte {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *TableName) GetQualifier() []byte {
	if m != nil {
		return m.Qualifier
	}
	return nil
}

// *
// Table Schema
// Inspired by the rest TableSchema
type TableSchema struct {
	TableName        *TableName            `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Attributes       []*BytesBytesPair     `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	ColumnFamilies   []*ColumnFamilySchema `protobuf:"bytes,3,rep,name=column_families,json=columnFamilies" json:"column_families,omitempty"`
	Configuration    []*NameStringPair     `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *TableSchema) Reset()                    { *m = TableSchema{} }
func (m *TableSchema) String() string            { return proto.CompactTextString(m) }
func (*TableSchema) ProtoMessage()               {}
func (*TableSchema) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *TableSchema) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *TableSchema) GetAttributes() []*BytesBytesPair {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *TableSchema) GetColumnFamilies() []*ColumnFamilySchema {
	if m != nil {
		return m.ColumnFamilies
	}
	return nil
}

func (m *TableSchema) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// * Denotes state of the table
type TableState struct {
	// This is the table's state.
	State            *TableState_State `protobuf:"varint,1,req,name=state,enum=pb.TableState_State" json:"state,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *TableState) Reset()                    { *m = TableState{} }
func (m *TableState) String() string            { return proto.CompactTextString(m) }
func (*TableState) ProtoMessage()               {}
func (*TableState) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *TableState) GetState() TableState_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return TableState_ENABLED
}

// *
// Column Family Schema
// Inspired by the rest ColumSchemaMessage
type ColumnFamilySchema struct {
	Name             []byte            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Attributes       []*BytesBytesPair `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	Configuration    []*NameStringPair `protobuf:"bytes,3,rep,name=configuration" json:"configuration,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ColumnFamilySchema) Reset()                    { *m = ColumnFamilySchema{} }
func (m *ColumnFamilySchema) String() string            { return proto.CompactTextString(m) }
func (*ColumnFamilySchema) ProtoMessage()               {}
func (*ColumnFamilySchema) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *ColumnFamilySchema) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ColumnFamilySchema) GetAttributes() []*BytesBytesPair {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *ColumnFamilySchema) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// *
// Protocol buffer version of HRegionInfo.
type RegionInfo struct {
	RegionId         *uint64    `protobuf:"varint,1,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	TableName        *TableName `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	StartKey         []byte     `protobuf:"bytes,3,opt,name=start_key,json=startKey" json:"start_key,omitempty"`
	EndKey           []byte     `protobuf:"bytes,4,opt,name=end_key,json=endKey" json:"end_key,omitempty"`
	Offline          *bool      `protobuf:"varint,5,opt,name=offline" json:"offline,omitempty"`
	Split            *bool      `protobuf:"varint,6,opt,name=split" json:"split,omitempty"`
	ReplicaId        *int32     `protobuf:"varint,7,opt,name=replica_id,json=replicaId,def=0" json:"replica_id,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *RegionInfo) Reset()                    { *m = RegionInfo{} }
func (m *RegionInfo) String() string            { return proto.CompactTextString(m) }
func (*RegionInfo) ProtoMessage()               {}
func (*RegionInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

const Default_RegionInfo_ReplicaId int32 = 0

func (m *RegionInfo) GetRegionId() uint64 {
	if m != nil && m.RegionId != nil {
		return *m.RegionId
	}
	return 0
}

func (m *RegionInfo) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *RegionInfo) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RegionInfo) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *RegionInfo) GetOffline() bool {
	if m != nil && m.Offline != nil {
		return *m.Offline
	}
	return false
}

func (m *RegionInfo) GetSplit() bool {
	if m != nil && m.Split != nil {
		return *m.Split
	}
	return false
}

func (m *RegionInfo) GetReplicaId() int32 {
	if m != nil && m.ReplicaId != nil {
		return *m.ReplicaId
	}
	return Default_RegionInfo_ReplicaId
}

// *
// Protocol buffer for favored nodes
type FavoredNodes struct {
	FavoredNode      []*ServerName `protobuf:"bytes,1,rep,name=favored_node,json=favoredNode" json:"favored_node,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *FavoredNodes) Reset()                    { *m = FavoredNodes{} }
func (m *FavoredNodes) String() string            { return proto.CompactTextString(m) }
func (*FavoredNodes) ProtoMessage()               {}
func (*FavoredNodes) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

func (m *FavoredNodes) GetFavoredNode() []*ServerName {
	if m != nil {
		return m.FavoredNode
	}
	return nil
}

// *
// Container protocol buffer to specify a region.
// You can specify region by region name, or the hash
// of the region name, which is known as encoded
// region name.
type RegionSpecifier struct {
	Type             *RegionSpecifier_RegionSpecifierType `protobuf:"varint,1,req,name=type,enum=pb.RegionSpecifier_RegionSpecifierType" json:"type,omitempty"`
	Value            []byte                               `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *RegionSpecifier) Reset()                    { *m = RegionSpecifier{} }
func (m *RegionSpecifier) String() string            { return proto.CompactTextString(m) }
func (*RegionSpecifier) ProtoMessage()               {}
func (*RegionSpecifier) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

func (m *RegionSpecifier) GetType() RegionSpecifier_RegionSpecifierType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RegionSpecifier_REGION_NAME
}

func (m *RegionSpecifier) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// *
// A range of time. Both from and to are Java time
// stamp in milliseconds. If you don't specify a time
// range, it means all time.  By default, if not
// specified, from = 0, and to = Long.MAX_VALUE
type TimeRange struct {
	From             *uint64 `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	To               *uint64 `protobuf:"varint,2,opt,name=to" json:"to,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TimeRange) Reset()                    { *m = TimeRange{} }
func (m *TimeRange) String() string            { return proto.CompactTextString(m) }
func (*TimeRange) ProtoMessage()               {}
func (*TimeRange) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{7} }

func (m *TimeRange) GetFrom() uint64 {
	if m != nil && m.From != nil {
		return *m.From
	}
	return 0
}

func (m *TimeRange) GetTo() uint64 {
	if m != nil && m.To != nil {
		return *m.To
	}
	return 0
}

// ColumnFamily Specific TimeRange
type ColumnFamilyTimeRange struct {
	ColumnFamily     []byte     `protobuf:"bytes,1,req,name=column_family,json=columnFamily" json:"column_family,omitempty"`
	TimeRange        *TimeRange `protobuf:"bytes,2,req,name=time_range,json=timeRange" json:"time_range,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *ColumnFamilyTimeRange) Reset()                    { *m = ColumnFamilyTimeRange{} }
func (m *ColumnFamilyTimeRange) String() string            { return proto.CompactTextString(m) }
func (*ColumnFamilyTimeRange) ProtoMessage()               {}
func (*ColumnFamilyTimeRange) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{8} }

func (m *ColumnFamilyTimeRange) GetColumnFamily() []byte {
	if m != nil {
		return m.ColumnFamily
	}
	return nil
}

func (m *ColumnFamilyTimeRange) GetTimeRange() *TimeRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

// *
// Protocol buffer version of ServerName
type ServerName struct {
	HostName         *string `protobuf:"bytes,1,req,name=host_name,json=hostName" json:"host_name,omitempty"`
	Port             *uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	StartCode        *uint64 `protobuf:"varint,3,opt,name=start_code,json=startCode" json:"start_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerName) Reset()                    { *m = ServerName{} }
func (m *ServerName) String() string            { return proto.CompactTextString(m) }
func (*ServerName) ProtoMessage()               {}
func (*ServerName) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{9} }

func (m *ServerName) GetHostName() string {
	if m != nil && m.HostName != nil {
		return *m.HostName
	}
	return ""
}

func (m *ServerName) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ServerName) GetStartCode() uint64 {
	if m != nil && m.StartCode != nil {
		return *m.StartCode
	}
	return 0
}

type Coprocessor struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Coprocessor) Reset()                    { *m = Coprocessor{} }
func (m *Coprocessor) String() string            { return proto.CompactTextString(m) }
func (*Coprocessor) ProtoMessage()               {}
func (*Coprocessor) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{10} }

func (m *Coprocessor) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type NameStringPair struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NameStringPair) Reset()                    { *m = NameStringPair{} }
func (m *NameStringPair) String() string            { return proto.CompactTextString(m) }
func (*NameStringPair) ProtoMessage()               {}
func (*NameStringPair) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{11} }

func (m *NameStringPair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NameStringPair) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type NameBytesPair struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            []byte  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NameBytesPair) Reset()                    { *m = NameBytesPair{} }
func (m *NameBytesPair) String() string            { return proto.CompactTextString(m) }
func (*NameBytesPair) ProtoMessage()               {}
func (*NameBytesPair) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{12} }

func (m *NameBytesPair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NameBytesPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type BytesBytesPair struct {
	First            []byte `protobuf:"bytes,1,req,name=first" json:"first,omitempty"`
	Second           []byte `protobuf:"bytes,2,req,name=second" json:"second,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BytesBytesPair) Reset()                    { *m = BytesBytesPair{} }
func (m *BytesBytesPair) String() string            { return proto.CompactTextString(m) }
func (*BytesBytesPair) ProtoMessage()               {}
func (*BytesBytesPair) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{13} }

func (m *BytesBytesPair) GetFirst() []byte {
	if m != nil {
		return m.First
	}
	return nil
}

func (m *BytesBytesPair) GetSecond() []byte {
	if m != nil {
		return m.Second
	}
	return nil
}

type NameInt64Pair struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value            *int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NameInt64Pair) Reset()                    { *m = NameInt64Pair{} }
func (m *NameInt64Pair) String() string            { return proto.CompactTextString(m) }
func (*NameInt64Pair) ProtoMessage()               {}
func (*NameInt64Pair) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{14} }

func (m *NameInt64Pair) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *NameInt64Pair) GetValue() int64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

// *
// Description of the distributed procedure to take
type ProcedureDescription struct {
	Signature        *string           `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	Instance         *string           `protobuf:"bytes,2,opt,name=instance" json:"instance,omitempty"`
	CreationTime     *int64            `protobuf:"varint,3,opt,name=creation_time,json=creationTime,def=0" json:"creation_time,omitempty"`
	Configuration    []*NameStringPair `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *ProcedureDescription) Reset()                    { *m = ProcedureDescription{} }
func (m *ProcedureDescription) String() string            { return proto.CompactTextString(m) }
func (*ProcedureDescription) ProtoMessage()               {}
func (*ProcedureDescription) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{15} }

const Default_ProcedureDescription_CreationTime int64 = 0

func (m *ProcedureDescription) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

func (m *ProcedureDescription) GetInstance() string {
	if m != nil && m.Instance != nil {
		return *m.Instance
	}
	return ""
}

func (m *ProcedureDescription) GetCreationTime() int64 {
	if m != nil && m.CreationTime != nil {
		return *m.CreationTime
	}
	return Default_ProcedureDescription_CreationTime
}

func (m *ProcedureDescription) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

type EmptyMsg struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *EmptyMsg) Reset()                    { *m = EmptyMsg{} }
func (m *EmptyMsg) String() string            { return proto.CompactTextString(m) }
func (*EmptyMsg) ProtoMessage()               {}
func (*EmptyMsg) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{16} }

type LongMsg struct {
	LongMsg          *int64 `protobuf:"varint,1,req,name=long_msg,json=longMsg" json:"long_msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *LongMsg) Reset()                    { *m = LongMsg{} }
func (m *LongMsg) String() string            { return proto.CompactTextString(m) }
func (*LongMsg) ProtoMessage()               {}
func (*LongMsg) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{17} }

func (m *LongMsg) GetLongMsg() int64 {
	if m != nil && m.LongMsg != nil {
		return *m.LongMsg
	}
	return 0
}

type DoubleMsg struct {
	DoubleMsg        *float64 `protobuf:"fixed64,1,req,name=double_msg,json=doubleMsg" json:"double_msg,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *DoubleMsg) Reset()                    { *m = DoubleMsg{} }
func (m *DoubleMsg) String() string            { return proto.CompactTextString(m) }
func (*DoubleMsg) ProtoMessage()               {}
func (*DoubleMsg) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{18} }

func (m *DoubleMsg) GetDoubleMsg() float64 {
	if m != nil && m.DoubleMsg != nil {
		return *m.DoubleMsg
	}
	return 0
}

type BigDecimalMsg struct {
	BigdecimalMsg    []byte `protobuf:"bytes,1,req,name=bigdecimal_msg,json=bigdecimalMsg" json:"bigdecimal_msg,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BigDecimalMsg) Reset()                    { *m = BigDecimalMsg{} }
func (m *BigDecimalMsg) String() string            { return proto.CompactTextString(m) }
func (*BigDecimalMsg) ProtoMessage()               {}
func (*BigDecimalMsg) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{19} }

func (m *BigDecimalMsg) GetBigdecimalMsg() []byte {
	if m != nil {
		return m.BigdecimalMsg
	}
	return nil
}

type UUID struct {
	LeastSigBits     *uint64 `protobuf:"varint,1,req,name=least_sig_bits,json=leastSigBits" json:"least_sig_bits,omitempty"`
	MostSigBits      *uint64 `protobuf:"varint,2,req,name=most_sig_bits,json=mostSigBits" json:"most_sig_bits,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UUID) Reset()                    { *m = UUID{} }
func (m *UUID) String() string            { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()               {}
func (*UUID) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{20} }

func (m *UUID) GetLeastSigBits() uint64 {
	if m != nil && m.LeastSigBits != nil {
		return *m.LeastSigBits
	}
	return 0
}

func (m *UUID) GetMostSigBits() uint64 {
	if m != nil && m.MostSigBits != nil {
		return *m.MostSigBits
	}
	return 0
}

type NamespaceDescriptor struct {
	Name             []byte            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Configuration    []*NameStringPair `protobuf:"bytes,2,rep,name=configuration" json:"configuration,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *NamespaceDescriptor) Reset()                    { *m = NamespaceDescriptor{} }
func (m *NamespaceDescriptor) String() string            { return proto.CompactTextString(m) }
func (*NamespaceDescriptor) ProtoMessage()               {}
func (*NamespaceDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{21} }

func (m *NamespaceDescriptor) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *NamespaceDescriptor) GetConfiguration() []*NameStringPair {
	if m != nil {
		return m.Configuration
	}
	return nil
}

// Rpc client version info proto. Included in ConnectionHeader on connection setup
type VersionInfo struct {
	Version          *string `protobuf:"bytes,1,req,name=version" json:"version,omitempty"`
	Url              *string `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	Revision         *string `protobuf:"bytes,3,req,name=revision" json:"revision,omitempty"`
	User             *string `protobuf:"bytes,4,req,name=user" json:"user,omitempty"`
	Date             *string `protobuf:"bytes,5,req,name=date" json:"date,omitempty"`
	SrcChecksum      *string `protobuf:"bytes,6,req,name=src_checksum,json=srcChecksum" json:"src_checksum,omitempty"`
	VersionMajor     *uint32 `protobuf:"varint,7,opt,name=version_major,json=versionMajor" json:"version_major,omitempty"`
	VersionMinor     *uint32 `protobuf:"varint,8,opt,name=version_minor,json=versionMinor" json:"version_minor,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VersionInfo) Reset()                    { *m = VersionInfo{} }
func (m *VersionInfo) String() string            { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()               {}
func (*VersionInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{22} }

func (m *VersionInfo) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *VersionInfo) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *VersionInfo) GetRevision() string {
	if m != nil && m.Revision != nil {
		return *m.Revision
	}
	return ""
}

func (m *VersionInfo) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *VersionInfo) GetDate() string {
	if m != nil && m.Date != nil {
		return *m.Date
	}
	return ""
}

func (m *VersionInfo) GetSrcChecksum() string {
	if m != nil && m.SrcChecksum != nil {
		return *m.SrcChecksum
	}
	return ""
}

func (m *VersionInfo) GetVersionMajor() uint32 {
	if m != nil && m.VersionMajor != nil {
		return *m.VersionMajor
	}
	return 0
}

func (m *VersionInfo) GetVersionMinor() uint32 {
	if m != nil && m.VersionMinor != nil {
		return *m.VersionMinor
	}
	return 0
}

// *
// Description of the region server info
type RegionServerInfo struct {
	InfoPort         *int32       `protobuf:"varint,1,opt,name=infoPort" json:"infoPort,omitempty"`
	VersionInfo      *VersionInfo `protobuf:"bytes,2,opt,name=version_info,json=versionInfo" json:"version_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *RegionServerInfo) Reset()                    { *m = RegionServerInfo{} }
func (m *RegionServerInfo) String() string            { return proto.CompactTextString(m) }
func (*RegionServerInfo) ProtoMessage()               {}
func (*RegionServerInfo) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{23} }

func (m *RegionServerInfo) GetInfoPort() int32 {
	if m != nil && m.InfoPort != nil {
		return *m.InfoPort
	}
	return 0
}

func (m *RegionServerInfo) GetVersionInfo() *VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*TableName)(nil), "pb.TableName")
	proto.RegisterType((*TableSchema)(nil), "pb.TableSchema")
	proto.RegisterType((*TableState)(nil), "pb.TableState")
	proto.RegisterType((*ColumnFamilySchema)(nil), "pb.ColumnFamilySchema")
	proto.RegisterType((*RegionInfo)(nil), "pb.RegionInfo")
	proto.RegisterType((*FavoredNodes)(nil), "pb.FavoredNodes")
	proto.RegisterType((*RegionSpecifier)(nil), "pb.RegionSpecifier")
	proto.RegisterType((*TimeRange)(nil), "pb.TimeRange")
	proto.RegisterType((*ColumnFamilyTimeRange)(nil), "pb.ColumnFamilyTimeRange")
	proto.RegisterType((*ServerName)(nil), "pb.ServerName")
	proto.RegisterType((*Coprocessor)(nil), "pb.Coprocessor")
	proto.RegisterType((*NameStringPair)(nil), "pb.NameStringPair")
	proto.RegisterType((*NameBytesPair)(nil), "pb.NameBytesPair")
	proto.RegisterType((*BytesBytesPair)(nil), "pb.BytesBytesPair")
	proto.RegisterType((*NameInt64Pair)(nil), "pb.NameInt64Pair")
	proto.RegisterType((*ProcedureDescription)(nil), "pb.ProcedureDescription")
	proto.RegisterType((*EmptyMsg)(nil), "pb.EmptyMsg")
	proto.RegisterType((*LongMsg)(nil), "pb.LongMsg")
	proto.RegisterType((*DoubleMsg)(nil), "pb.DoubleMsg")
	proto.RegisterType((*BigDecimalMsg)(nil), "pb.BigDecimalMsg")
	proto.RegisterType((*UUID)(nil), "pb.UUID")
	proto.RegisterType((*NamespaceDescriptor)(nil), "pb.NamespaceDescriptor")
	proto.RegisterType((*VersionInfo)(nil), "pb.VersionInfo")
	proto.RegisterType((*RegionServerInfo)(nil), "pb.RegionServerInfo")
	proto.RegisterEnum("pb.CompareType", CompareType_name, CompareType_value)
	proto.RegisterEnum("pb.TimeUnit", TimeUnit_name, TimeUnit_value)
	proto.RegisterEnum("pb.TableState_State", TableState_State_name, TableState_State_value)
	proto.RegisterEnum("pb.RegionSpecifier_RegionSpecifierType", RegionSpecifier_RegionSpecifierType_name, RegionSpecifier_RegionSpecifierType_value)
}

var fileDescriptor12 = []byte{
	// 1298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0xfe, 0xa9, 0x83, 0x25, 0x8d, 0x0e, 0xd6, 0xbf, 0x49, 0x13, 0xf7, 0x04, 0x24, 0x6c, 0xda,
	0x06, 0x46, 0xa1, 0x36, 0x46, 0x11, 0xb4, 0x29, 0xd0, 0x40, 0x07, 0xc6, 0x11, 0x6a, 0x53, 0xee,
	0xd2, 0x2e, 0x50, 0xa0, 0x00, 0x41, 0x91, 0x2b, 0x9a, 0x89, 0x44, 0xaa, 0x4b, 0xca, 0x80, 0x5e,
	0xa4, 0xd7, 0xbd, 0xe9, 0x0b, 0xf4, 0x85, 0x7a, 0xdf, 0xa7, 0xe8, 0xcc, 0x2e, 0x29, 0x59, 0x8e,
	0xd1, 0x06, 0xed, 0x8d, 0x34, 0xf3, 0xcd, 0xcc, 0x1e, 0x66, 0xbe, 0x99, 0x25, 0x34, 0x5f, 0x0e,
	0xbc, 0x54, 0xf4, 0x96, 0x32, 0xc9, 0x12, 0x56, 0x5a, 0x4e, 0xcd, 0x63, 0x68, 0x9c, 0x7b, 0xd3,
	0xb9, 0xb0, 0xbd, 0x85, 0x60, 0x1f, 0x40, 0x23, 0xc6, 0xff, 0x74, 0xe9, 0xf9, 0xe2, 0xc0, 0x78,
	0x50, 0x7a, 0xdc, 0xe2, 0x5b, 0x80, 0xac, 0x3f, 0xaf, 0xbc, 0x79, 0x34, 0x8b, 0x84, 0x3c, 0x28,
	0x69, 0xeb, 0x06, 0x30, 0xff, 0x34, 0xa0, 0xa9, 0x56, 0x72, 0xfc, 0x4b, 0xb1, 0xf0, 0xd8, 0x67,
	0x00, 0x19, 0xa9, 0x2e, 0x2d, 0x80, 0x8b, 0x19, 0x8f, 0x9b, 0x47, 0xed, 0xde, 0x72, 0xda, 0xdb,
	0x6c, 0xc7, 0x1b, 0xd9, 0x66, 0xe7, 0x23, 0x00, 0x2f, 0xcb, 0x64, 0x34, 0x5d, 0x65, 0x22, 0xc5,
	0xc5, 0xcb, 0xe8, 0xcd, 0xc8, 0x7b, 0xb0, 0x46, 0x40, 0xfd, 0x9c, 0x79, 0x91, 0xe4, 0xd7, 0xbc,
	0xd8, 0x73, 0xd8, 0xf7, 0x93, 0xf9, 0x6a, 0x11, 0xbb, 0x33, 0x6f, 0x11, 0xcd, 0x23, 0x0c, 0x2c,
	0xab, 0xc0, 0x7b, 0x14, 0x38, 0x54, 0xa6, 0x17, 0x64, 0x59, 0xeb, 0x23, 0xf1, 0x8e, 0xbf, 0xc5,
	0xd0, 0x9b, 0x7d, 0x05, 0x6d, 0x3f, 0x89, 0x67, 0x51, 0xb8, 0x92, 0x5e, 0x16, 0x25, 0xf1, 0x41,
	0x65, 0xbb, 0x2f, 0x9d, 0xca, 0xc1, 0xad, 0xe2, 0x50, 0xed, 0xbb, 0xeb, 0x68, 0xae, 0x01, 0xf4,
	0x5d, 0x33, 0x2f, 0x13, 0xec, 0x10, 0xaa, 0x29, 0x09, 0x2a, 0x65, 0x9d, 0xa3, 0xbb, 0x9b, 0x5b,
	0x2a, 0x73, 0x4f, 0xfd, 0x72, 0xed, 0x62, 0x3e, 0x87, 0xaa, 0x0e, 0x6a, 0x42, 0xcd, 0xb2, 0xfb,
	0x83, 0x13, 0x6b, 0xd4, 0xfd, 0x1f, 0x6b, 0x41, 0x7d, 0x34, 0x76, 0xb4, 0x66, 0xb0, 0x36, 0x34,
	0xb4, 0x36, 0xb6, 0x8f, 0xbb, 0x25, 0x32, 0x2a, 0x4f, 0xd2, 0xca, 0xe6, 0x2f, 0x06, 0xb0, 0x37,
	0xef, 0xc6, 0x18, 0x54, 0xf2, 0x44, 0x53, 0x5d, 0x94, 0xfc, 0xaf, 0x92, 0xfa, 0x46, 0x4e, 0xca,
	0x6f, 0x9b, 0x93, 0x3f, 0x0c, 0x00, 0x2e, 0x42, 0x14, 0xc7, 0xf1, 0x2c, 0x61, 0xef, 0x43, 0x43,
	0x2a, 0xcd, 0x8d, 0x02, 0x75, 0xaa, 0x0a, 0xaf, 0x6b, 0x60, 0x1c, 0xdc, 0x20, 0x07, 0x71, 0xe9,
	0xef, 0xc8, 0x81, 0x4b, 0x61, 0xf2, 0x64, 0xe6, 0xbe, 0x16, 0x6b, 0x3c, 0x8f, 0x81, 0x17, 0xac,
	0x2b, 0xe0, 0x3b, 0xb1, 0x66, 0xf7, 0xa1, 0x26, 0xe2, 0x40, 0x99, 0x2a, 0xca, 0xb4, 0x87, 0x2a,
	0x19, 0x0e, 0xa0, 0x96, 0xcc, 0x66, 0xf3, 0x28, 0x16, 0x07, 0x55, 0x34, 0xd4, 0x79, 0xa1, 0xb2,
	0xbb, 0x58, 0xaf, 0xe5, 0x3c, 0xca, 0x0e, 0xf6, 0x14, 0xae, 0x15, 0xf6, 0x00, 0x40, 0x0a, 0x94,
	0x7c, 0x8f, 0x4e, 0x5c, 0x43, 0x53, 0xf5, 0x99, 0xf1, 0x05, 0x6f, 0xe4, 0xe0, 0x38, 0x30, 0xfb,
	0xd0, 0x7a, 0xe1, 0x5d, 0x25, 0x52, 0x04, 0x76, 0x12, 0x60, 0xae, 0x9e, 0x40, 0x6b, 0xa6, 0x75,
	0x37, 0x46, 0x00, 0x6f, 0x49, 0xa9, 0xea, 0xd0, 0x3d, 0x1c, 0x21, 0xaf, 0x84, 0x54, 0x17, 0x69,
	0xce, 0xb6, 0x31, 0xe6, 0x6f, 0x06, 0xec, 0xeb, 0x24, 0x39, 0x4b, 0xe1, 0xab, 0xce, 0x61, 0xdf,
	0x40, 0x25, 0x5b, 0x2f, 0x0b, 0xf6, 0x7c, 0x4a, 0xe1, 0x37, 0x5c, 0x6e, 0xea, 0xe7, 0xe8, 0xce,
	0x55, 0x10, 0xdd, 0xe5, 0xca, 0x9b, 0xaf, 0x44, 0xde, 0x90, 0x5a, 0x41, 0x96, 0xdd, 0xb9, 0x25,
	0x84, 0xed, 0x43, 0x93, 0x5b, 0xc7, 0xe3, 0x89, 0xed, 0xda, 0xfd, 0x53, 0x0b, 0x99, 0x76, 0x1f,
	0xee, 0x58, 0xf6, 0x70, 0x32, 0xb2, 0x46, 0xee, 0x75, 0x43, 0xc9, 0xfc, 0x1c, 0xc7, 0x42, 0x84,
	0x87, 0xf7, 0xe2, 0x50, 0x10, 0xb7, 0x66, 0x32, 0x59, 0xa8, 0x26, 0xae, 0x70, 0x25, 0xb3, 0x0e,
	0x94, 0xb2, 0x04, 0x37, 0x25, 0x04, 0x25, 0xf3, 0x15, 0xbc, 0x73, 0x9d, 0x95, 0xdb, 0xe0, 0x8f,
	0x88, 0x50, 0xdb, 0x2e, 0x5d, 0xe7, 0x0c, 0x6d, 0x5d, 0xeb, 0xc5, 0xb5, 0xe2, 0x03, 0x46, 0xb8,
	0x92, 0x42, 0x76, 0xf8, 0x50, 0xac, 0x83, 0x7c, 0x28, 0x44, 0xf3, 0x27, 0x80, 0x6d, 0x7e, 0x89,
	0x1d, 0x97, 0x49, 0x9a, 0xb9, 0x1b, 0xfa, 0x37, 0x78, 0x9d, 0x00, 0x65, 0xc4, 0xa3, 0x2f, 0x13,
	0x99, 0xa9, 0x83, 0xb6, 0xb9, 0x92, 0xd9, 0x87, 0x00, 0x9a, 0x4e, 0x3e, 0x15, 0xad, 0xac, 0xae,
	0xa0, 0x09, 0x36, 0xa4, 0x12, 0x3d, 0x84, 0xe6, 0x30, 0xc1, 0x01, 0xe9, 0x8b, 0x34, 0x4d, 0xe4,
	0x4e, 0x63, 0x35, 0x74, 0x63, 0x99, 0xcf, 0xa0, 0xb3, 0xdb, 0x0b, 0xb7, 0x79, 0xed, 0x96, 0xa6,
	0x51, 0x94, 0xe6, 0x6b, 0x68, 0x53, 0xec, 0xa6, 0xfb, 0xfe, 0x29, 0xd4, 0xd8, 0x56, 0xf5, 0x5b,
	0xe8, 0xec, 0x76, 0x2e, 0xf9, 0xcd, 0x22, 0x99, 0x66, 0x79, 0x52, 0xb5, 0xc2, 0xee, 0xc1, 0x5e,
	0x2a, 0xb0, 0x39, 0x83, 0x9c, 0x14, 0xb9, 0x56, 0x6c, 0x3d, 0x8e, 0xb3, 0xa7, 0x5f, 0xde, 0xd8,
	0xda, 0xb8, 0x7d, 0xeb, 0x72, 0xb1, 0xf5, 0xef, 0x06, 0xdc, 0x3d, 0xa3, 0x9c, 0x04, 0x2b, 0x29,
	0x46, 0x22, 0xf5, 0x65, 0xb4, 0xa4, 0xae, 0xa7, 0x47, 0x21, 0x8d, 0xc2, 0xd8, 0xcb, 0x10, 0xcf,
	0xaf, 0xb0, 0x05, 0xd8, 0x7b, 0x50, 0x8f, 0x62, 0x4c, 0x6d, 0xec, 0xeb, 0xf5, 0xb0, 0x34, 0x85,
	0xce, 0x3e, 0x41, 0x62, 0x48, 0xa1, 0x66, 0x87, 0x4b, 0xb5, 0x55, 0x95, 0x28, 0x53, 0xcb, 0xb5,
	0x0a, 0x9c, 0xaa, 0xff, 0x1f, 0xa6, 0x34, 0xe0, 0xe0, 0x5c, 0x2c, 0xb3, 0xf5, 0x69, 0x1a, 0x9a,
	0x8f, 0xa0, 0x76, 0x92, 0xc4, 0x21, 0x8a, 0xec, 0x5d, 0xa8, 0xcf, 0x51, 0x74, 0x17, 0x69, 0xa8,
	0x4e, 0x5c, 0xe6, 0xb5, 0xb9, 0x36, 0x99, 0x87, 0x38, 0x79, 0x93, 0x15, 0xce, 0x1d, 0xf2, 0x43,
	0x9e, 0x04, 0x4a, 0xd9, 0x78, 0x1a, 0xbc, 0x11, 0x14, 0x66, 0xf3, 0x29, 0xb4, 0x07, 0x51, 0x38,
	0xc2, 0xfe, 0x5a, 0x78, 0x73, 0xf2, 0xff, 0x18, 0x3a, 0xd3, 0x28, 0x0c, 0x34, 0xb0, 0x89, 0x69,
	0xf1, 0xf6, 0x16, 0xa5, 0xb8, 0x33, 0xa8, 0x5c, 0x5c, 0x8c, 0x47, 0xec, 0x11, 0x74, 0xe6, 0xc2,
	0x43, 0xe2, 0x62, 0xba, 0xdc, 0x69, 0x94, 0xa5, 0xf9, 0x94, 0x6c, 0x29, 0xd4, 0x89, 0xc2, 0x01,
	0x62, 0xcc, 0x84, 0xf6, 0x22, 0xb9, 0xee, 0x54, 0x52, 0x4e, 0x4d, 0x02, 0x73, 0x1f, 0xd3, 0x87,
	0x3b, 0x76, 0xf1, 0x4a, 0x17, 0xb5, 0xb9, 0xc1, 0xdc, 0xe2, 0x49, 0x78, 0x23, 0x99, 0xa5, 0xb7,
	0x4d, 0x26, 0xbd, 0xef, 0x3f, 0x08, 0x99, 0x16, 0xf3, 0x1d, 0xc7, 0xeb, 0x95, 0x56, 0xf3, 0xb2,
	0x17, 0x2a, 0xeb, 0x42, 0x79, 0x25, 0xe7, 0x39, 0xeb, 0x49, 0x24, 0x1a, 0x48, 0x71, 0x15, 0xa5,
	0xfa, 0x3d, 0x51, 0x1d, 0x5a, 0xe8, 0x74, 0xca, 0x55, 0x8a, 0x1f, 0x14, 0x15, 0x4d, 0x7f, 0x92,
	0x09, 0x0b, 0xe8, 0x3d, 0xad, 0x6a, 0x8c, 0x64, 0xf6, 0x10, 0x5a, 0xa9, 0xf4, 0x5d, 0x7c, 0xed,
	0xfc, 0xd7, 0xe9, 0x6a, 0x81, 0xb3, 0x9b, 0x6c, 0x4d, 0xc4, 0x86, 0x39, 0x44, 0xa3, 0x26, 0x3f,
	0x83, 0xbb, 0xf0, 0x5e, 0x25, 0x52, 0x0d, 0xf1, 0x36, 0x6f, 0xe5, 0xe0, 0x29, 0x61, 0x3b, 0x4e,
	0x51, 0x8c, 0x4e, 0xf5, 0x5d, 0x27, 0xc2, 0xcc, 0x29, 0x74, 0xf3, 0xf9, 0xa9, 0xe6, 0x8c, 0xba,
	0xb0, 0xe2, 0xf2, 0x2c, 0x39, 0xa3, 0x71, 0x42, 0x0d, 0x53, 0xe5, 0x1b, 0x1d, 0x5f, 0xda, 0x22,
	0xde, 0x25, 0x4c, 0x71, 0xbd, 0x79, 0xb4, 0x4f, 0x59, 0xbd, 0x96, 0x33, 0xde, 0xbc, 0xda, 0x2a,
	0x87, 0x92, 0xe6, 0xcc, 0x62, 0xe9, 0x49, 0xa1, 0x66, 0x73, 0x1d, 0x2a, 0x27, 0x96, 0xe3, 0xe0,
	0xc7, 0xc0, 0xff, 0xa1, 0x4d, 0x92, 0x3b, 0xe1, 0xae, 0xf5, 0xfd, 0x45, 0xff, 0x04, 0xe7, 0x74,
	0x03, 0xaa, 0x5a, 0x2c, 0xd1, 0xc7, 0x81, 0x3d, 0x39, 0xcf, 0x2d, 0x65, 0x6c, 0xd7, 0xee, 0x31,
	0xb7, 0xfa, 0xe7, 0x16, 0xdf, 0xfa, 0x57, 0xe8, 0xe3, 0x22, 0x47, 0xbb, 0x55, 0x0a, 0xb6, 0x27,
	0xee, 0xe4, 0xac, 0xbb, 0x77, 0x18, 0x43, 0x9d, 0x7a, 0xea, 0x22, 0xc6, 0xf7, 0x0e, 0x1f, 0x03,
	0xbb, 0x6f, 0x4f, 0x1c, 0x6b, 0x38, 0xb1, 0x47, 0x0e, 0x6e, 0xd2, 0x85, 0xd6, 0xe9, 0x78, 0xc8,
	0x37, 0x48, 0x49, 0x23, 0x27, 0x27, 0xe3, 0x02, 0x29, 0xd3, 0xc2, 0x85, 0xa2, 0x76, 0x39, 0x1d,
	0xdb, 0x17, 0xe7, 0x96, 0xa3, 0x77, 0x79, 0x39, 0xb9, 0xe0, 0x4e, 0x77, 0x8f, 0xae, 0x32, 0xea,
	0xff, 0xe8, 0x74, 0x6b, 0x03, 0x0b, 0x9e, 0x24, 0x32, 0xec, 0x79, 0xc8, 0xcc, 0x4b, 0xd1, 0xbb,
	0xf4, 0x82, 0x24, 0x59, 0xf6, 0x2e, 0xa7, 0xf4, 0x09, 0x9a, 0xa2, 0x26, 0x02, 0xfd, 0x25, 0x3a,
	0x5d, 0xcd, 0x7a, 0xa1, 0x88, 0x05, 0x52, 0x4d, 0x04, 0x03, 0xfd, 0x8d, 0x7a, 0x46, 0x86, 0xf4,
	0xa5, 0xf1, 0xab, 0x61, 0xfc, 0x15, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x63, 0x91, 0x73, 0xb6, 0x0a,
	0x00, 0x00,
}
