// Code generated by protoc-gen-go.
// source: RegionServerStatus.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RegionStateTransition_TransitionCode int32

const (
	RegionStateTransition_OPENED      RegionStateTransition_TransitionCode = 0
	RegionStateTransition_FAILED_OPEN RegionStateTransition_TransitionCode = 1
	// * No failed_close, in which case region server will abort
	RegionStateTransition_CLOSED RegionStateTransition_TransitionCode = 2
	// * Ask master for ok to split/merge region(s)
	RegionStateTransition_READY_TO_SPLIT RegionStateTransition_TransitionCode = 3
	RegionStateTransition_READY_TO_MERGE RegionStateTransition_TransitionCode = 4
	RegionStateTransition_SPLIT_PONR     RegionStateTransition_TransitionCode = 5
	RegionStateTransition_MERGE_PONR     RegionStateTransition_TransitionCode = 6
	RegionStateTransition_SPLIT          RegionStateTransition_TransitionCode = 7
	RegionStateTransition_MERGED         RegionStateTransition_TransitionCode = 8
	RegionStateTransition_SPLIT_REVERTED RegionStateTransition_TransitionCode = 9
	RegionStateTransition_MERGE_REVERTED RegionStateTransition_TransitionCode = 10
)

var RegionStateTransition_TransitionCode_name = map[int32]string{
	0:  "OPENED",
	1:  "FAILED_OPEN",
	2:  "CLOSED",
	3:  "READY_TO_SPLIT",
	4:  "READY_TO_MERGE",
	5:  "SPLIT_PONR",
	6:  "MERGE_PONR",
	7:  "SPLIT",
	8:  "MERGED",
	9:  "SPLIT_REVERTED",
	10: "MERGE_REVERTED",
}
var RegionStateTransition_TransitionCode_value = map[string]int32{
	"OPENED":         0,
	"FAILED_OPEN":    1,
	"CLOSED":         2,
	"READY_TO_SPLIT": 3,
	"READY_TO_MERGE": 4,
	"SPLIT_PONR":     5,
	"MERGE_PONR":     6,
	"SPLIT":          7,
	"MERGED":         8,
	"SPLIT_REVERTED": 9,
	"MERGE_REVERTED": 10,
}

func (x RegionStateTransition_TransitionCode) Enum() *RegionStateTransition_TransitionCode {
	p := new(RegionStateTransition_TransitionCode)
	*p = x
	return p
}
func (x RegionStateTransition_TransitionCode) String() string {
	return proto.EnumName(RegionStateTransition_TransitionCode_name, int32(x))
}
func (x *RegionStateTransition_TransitionCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegionStateTransition_TransitionCode_value, data, "RegionStateTransition_TransitionCode")
	if err != nil {
		return err
	}
	*x = RegionStateTransition_TransitionCode(value)
	return nil
}
func (RegionStateTransition_TransitionCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor21, []int{8, 0}
}

type RegionServerStartupRequest struct {
	// * Port number this regionserver is up on
	Port *uint32 `protobuf:"varint,1,req,name=port" json:"port,omitempty"`
	// * This servers' startcode
	ServerStartCode *uint64 `protobuf:"varint,2,req,name=server_start_code,json=serverStartCode" json:"server_start_code,omitempty"`
	// * Current time of the region server in ms
	ServerCurrentTime *uint64 `protobuf:"varint,3,req,name=server_current_time,json=serverCurrentTime" json:"server_current_time,omitempty"`
	// * hostname for region server, optional
	UseThisHostnameInstead *string `protobuf:"bytes,4,opt,name=use_this_hostname_instead,json=useThisHostnameInstead" json:"use_this_hostname_instead,omitempty"`
	XXX_unrecognized       []byte  `json:"-"`
}

func (m *RegionServerStartupRequest) Reset()                    { *m = RegionServerStartupRequest{} }
func (m *RegionServerStartupRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionServerStartupRequest) ProtoMessage()               {}
func (*RegionServerStartupRequest) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{0} }

func (m *RegionServerStartupRequest) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *RegionServerStartupRequest) GetServerStartCode() uint64 {
	if m != nil && m.ServerStartCode != nil {
		return *m.ServerStartCode
	}
	return 0
}

func (m *RegionServerStartupRequest) GetServerCurrentTime() uint64 {
	if m != nil && m.ServerCurrentTime != nil {
		return *m.ServerCurrentTime
	}
	return 0
}

func (m *RegionServerStartupRequest) GetUseThisHostnameInstead() string {
	if m != nil && m.UseThisHostnameInstead != nil {
		return *m.UseThisHostnameInstead
	}
	return ""
}

type RegionServerStartupResponse struct {
	// *
	// Configuration for the regionserver to use: e.g. filesystem,
	// hbase rootdir, the hostname to use creating the RegionServer ServerName,
	// etc
	MapEntries       []*NameStringPair `protobuf:"bytes,1,rep,name=map_entries,json=mapEntries" json:"map_entries,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RegionServerStartupResponse) Reset()                    { *m = RegionServerStartupResponse{} }
func (m *RegionServerStartupResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionServerStartupResponse) ProtoMessage()               {}
func (*RegionServerStartupResponse) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{1} }

func (m *RegionServerStartupResponse) GetMapEntries() []*NameStringPair {
	if m != nil {
		return m.MapEntries
	}
	return nil
}

type RegionServerReportRequest struct {
	Server *ServerName `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	// * load the server is under
	Load             *ServerLoad `protobuf:"bytes,2,opt,name=load" json:"load,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RegionServerReportRequest) Reset()                    { *m = RegionServerReportRequest{} }
func (m *RegionServerReportRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionServerReportRequest) ProtoMessage()               {}
func (*RegionServerReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{2} }

func (m *RegionServerReportRequest) GetServer() *ServerName {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *RegionServerReportRequest) GetLoad() *ServerLoad {
	if m != nil {
		return m.Load
	}
	return nil
}

type RegionServerReportResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegionServerReportResponse) Reset()                    { *m = RegionServerReportResponse{} }
func (m *RegionServerReportResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionServerReportResponse) ProtoMessage()               {}
func (*RegionServerReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{3} }

type ReportRSFatalErrorRequest struct {
	// * name of the server experiencing the error
	Server *ServerName `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	// * informative text to expose in the master logs and UI
	ErrorMessage     *string `protobuf:"bytes,2,req,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReportRSFatalErrorRequest) Reset()                    { *m = ReportRSFatalErrorRequest{} }
func (m *ReportRSFatalErrorRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportRSFatalErrorRequest) ProtoMessage()               {}
func (*ReportRSFatalErrorRequest) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{4} }

func (m *ReportRSFatalErrorRequest) GetServer() *ServerName {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ReportRSFatalErrorRequest) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type ReportRSFatalErrorResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReportRSFatalErrorResponse) Reset()                    { *m = ReportRSFatalErrorResponse{} }
func (m *ReportRSFatalErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportRSFatalErrorResponse) ProtoMessage()               {}
func (*ReportRSFatalErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{5} }

type GetLastFlushedSequenceIdRequest struct {
	// * region name
	RegionName       []byte `protobuf:"bytes,1,req,name=region_name,json=regionName" json:"region_name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetLastFlushedSequenceIdRequest) Reset()         { *m = GetLastFlushedSequenceIdRequest{} }
func (m *GetLastFlushedSequenceIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetLastFlushedSequenceIdRequest) ProtoMessage()    {}
func (*GetLastFlushedSequenceIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{6}
}

func (m *GetLastFlushedSequenceIdRequest) GetRegionName() []byte {
	if m != nil {
		return m.RegionName
	}
	return nil
}

type GetLastFlushedSequenceIdResponse struct {
	// * the last WAL sequence id flushed from MemStore to HFile for the region
	LastFlushedSequenceId *uint64 `protobuf:"varint,1,req,name=last_flushed_sequence_id,json=lastFlushedSequenceId" json:"last_flushed_sequence_id,omitempty"`
	// * the last WAL sequence id flushed from MemStore to HFile for stores of the region
	StoreLastFlushedSequenceId []*StoreSequenceId `protobuf:"bytes,2,rep,name=store_last_flushed_sequence_id,json=storeLastFlushedSequenceId" json:"store_last_flushed_sequence_id,omitempty"`
	XXX_unrecognized           []byte             `json:"-"`
}

func (m *GetLastFlushedSequenceIdResponse) Reset()         { *m = GetLastFlushedSequenceIdResponse{} }
func (m *GetLastFlushedSequenceIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetLastFlushedSequenceIdResponse) ProtoMessage()    {}
func (*GetLastFlushedSequenceIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{7}
}

func (m *GetLastFlushedSequenceIdResponse) GetLastFlushedSequenceId() uint64 {
	if m != nil && m.LastFlushedSequenceId != nil {
		return *m.LastFlushedSequenceId
	}
	return 0
}

func (m *GetLastFlushedSequenceIdResponse) GetStoreLastFlushedSequenceId() []*StoreSequenceId {
	if m != nil {
		return m.StoreLastFlushedSequenceId
	}
	return nil
}

type RegionStateTransition struct {
	TransitionCode *RegionStateTransition_TransitionCode `protobuf:"varint,1,req,name=transition_code,json=transitionCode,enum=pb.RegionStateTransition_TransitionCode" json:"transition_code,omitempty"`
	// * Mutliple regions are involved during merging/splitting
	RegionInfo []*RegionInfo `protobuf:"bytes,2,rep,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	// * For newly opened region, the open seq num is needed
	OpenSeqNum       *uint64 `protobuf:"varint,3,opt,name=open_seq_num,json=openSeqNum" json:"open_seq_num,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegionStateTransition) Reset()                    { *m = RegionStateTransition{} }
func (m *RegionStateTransition) String() string            { return proto.CompactTextString(m) }
func (*RegionStateTransition) ProtoMessage()               {}
func (*RegionStateTransition) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{8} }

func (m *RegionStateTransition) GetTransitionCode() RegionStateTransition_TransitionCode {
	if m != nil && m.TransitionCode != nil {
		return *m.TransitionCode
	}
	return RegionStateTransition_OPENED
}

func (m *RegionStateTransition) GetRegionInfo() []*RegionInfo {
	if m != nil {
		return m.RegionInfo
	}
	return nil
}

func (m *RegionStateTransition) GetOpenSeqNum() uint64 {
	if m != nil && m.OpenSeqNum != nil {
		return *m.OpenSeqNum
	}
	return 0
}

type ReportRegionStateTransitionRequest struct {
	// * This region server's server name
	Server           *ServerName              `protobuf:"bytes,1,req,name=server" json:"server,omitempty"`
	Transition       []*RegionStateTransition `protobuf:"bytes,2,rep,name=transition" json:"transition,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ReportRegionStateTransitionRequest) Reset()         { *m = ReportRegionStateTransitionRequest{} }
func (m *ReportRegionStateTransitionRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRegionStateTransitionRequest) ProtoMessage()    {}
func (*ReportRegionStateTransitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{9}
}

func (m *ReportRegionStateTransitionRequest) GetServer() *ServerName {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *ReportRegionStateTransitionRequest) GetTransition() []*RegionStateTransition {
	if m != nil {
		return m.Transition
	}
	return nil
}

type ReportRegionStateTransitionResponse struct {
	// * Error message if failed to update the region state
	ErrorMessage     *string `protobuf:"bytes,1,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReportRegionStateTransitionResponse) Reset()         { *m = ReportRegionStateTransitionResponse{} }
func (m *ReportRegionStateTransitionResponse) String() string { return proto.CompactTextString(m) }
func (*ReportRegionStateTransitionResponse) ProtoMessage()    {}
func (*ReportRegionStateTransitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor21, []int{10}
}

func (m *ReportRegionStateTransitionResponse) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}

type RegionSpaceUse struct {
	RegionInfo       *RegionInfo `protobuf:"bytes,1,opt,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	RegionSize       *uint64     `protobuf:"varint,2,opt,name=region_size,json=regionSize" json:"region_size,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *RegionSpaceUse) Reset()                    { *m = RegionSpaceUse{} }
func (m *RegionSpaceUse) String() string            { return proto.CompactTextString(m) }
func (*RegionSpaceUse) ProtoMessage()               {}
func (*RegionSpaceUse) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{11} }

func (m *RegionSpaceUse) GetRegionInfo() *RegionInfo {
	if m != nil {
		return m.RegionInfo
	}
	return nil
}

func (m *RegionSpaceUse) GetRegionSize() uint64 {
	if m != nil && m.RegionSize != nil {
		return *m.RegionSize
	}
	return 0
}

// *
// Reports filesystem usage for regions.
type RegionSpaceUseReportRequest struct {
	SpaceUse         []*RegionSpaceUse `protobuf:"bytes,1,rep,name=space_use,json=spaceUse" json:"space_use,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RegionSpaceUseReportRequest) Reset()                    { *m = RegionSpaceUseReportRequest{} }
func (m *RegionSpaceUseReportRequest) String() string            { return proto.CompactTextString(m) }
func (*RegionSpaceUseReportRequest) ProtoMessage()               {}
func (*RegionSpaceUseReportRequest) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{12} }

func (m *RegionSpaceUseReportRequest) GetSpaceUse() []*RegionSpaceUse {
	if m != nil {
		return m.SpaceUse
	}
	return nil
}

type RegionSpaceUseReportResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RegionSpaceUseReportResponse) Reset()                    { *m = RegionSpaceUseReportResponse{} }
func (m *RegionSpaceUseReportResponse) String() string            { return proto.CompactTextString(m) }
func (*RegionSpaceUseReportResponse) ProtoMessage()               {}
func (*RegionSpaceUseReportResponse) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{13} }

func init() {
	proto.RegisterType((*RegionServerStartupRequest)(nil), "pb.RegionServerStartupRequest")
	proto.RegisterType((*RegionServerStartupResponse)(nil), "pb.RegionServerStartupResponse")
	proto.RegisterType((*RegionServerReportRequest)(nil), "pb.RegionServerReportRequest")
	proto.RegisterType((*RegionServerReportResponse)(nil), "pb.RegionServerReportResponse")
	proto.RegisterType((*ReportRSFatalErrorRequest)(nil), "pb.ReportRSFatalErrorRequest")
	proto.RegisterType((*ReportRSFatalErrorResponse)(nil), "pb.ReportRSFatalErrorResponse")
	proto.RegisterType((*GetLastFlushedSequenceIdRequest)(nil), "pb.GetLastFlushedSequenceIdRequest")
	proto.RegisterType((*GetLastFlushedSequenceIdResponse)(nil), "pb.GetLastFlushedSequenceIdResponse")
	proto.RegisterType((*RegionStateTransition)(nil), "pb.RegionStateTransition")
	proto.RegisterType((*ReportRegionStateTransitionRequest)(nil), "pb.ReportRegionStateTransitionRequest")
	proto.RegisterType((*ReportRegionStateTransitionResponse)(nil), "pb.ReportRegionStateTransitionResponse")
	proto.RegisterType((*RegionSpaceUse)(nil), "pb.RegionSpaceUse")
	proto.RegisterType((*RegionSpaceUseReportRequest)(nil), "pb.RegionSpaceUseReportRequest")
	proto.RegisterType((*RegionSpaceUseReportResponse)(nil), "pb.RegionSpaceUseReportResponse")
	proto.RegisterEnum("pb.RegionStateTransition_TransitionCode", RegionStateTransition_TransitionCode_name, RegionStateTransition_TransitionCode_value)
}

var fileDescriptor21 = []byte{
	// 921 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x72, 0x1b, 0x45,
	0x10, 0x66, 0x65, 0xc5, 0x44, 0x2d, 0x47, 0x16, 0x63, 0x42, 0xc9, 0x22, 0xd8, 0xaa, 0x35, 0x15,
	0x5c, 0x1c, 0x36, 0x85, 0x39, 0x50, 0x39, 0xc6, 0xf6, 0x3a, 0x16, 0xa5, 0xc8, 0x62, 0x56, 0x09,
	0x95, 0xd3, 0xd4, 0x4a, 0x1a, 0x4b, 0x5b, 0x25, 0xed, 0x2e, 0x33, 0xb3, 0x1c, 0x38, 0x71, 0x83,
	0xc7, 0xe0, 0x21, 0x78, 0x00, 0x6e, 0x1c, 0x79, 0x25, 0xe6, 0x6f, 0x2d, 0xad, 0xb5, 0xeb, 0x54,
	0x6e, 0x3b, 0xdd, 0x5f, 0x7f, 0xfd, 0x4d, 0xf7, 0x74, 0x4b, 0xd0, 0xc1, 0x74, 0x1e, 0x25, 0x71,
	0x40, 0xd9, 0xaf, 0x94, 0x05, 0x22, 0x14, 0x19, 0xf7, 0x52, 0x96, 0x88, 0x04, 0xd5, 0xd2, 0x49,
	0xb7, 0x79, 0x7d, 0x1e, 0x72, 0x6a, 0x0c, 0xdd, 0x83, 0x8b, 0x65, 0xc6, 0x45, 0x11, 0xe5, 0xfe,
	0xeb, 0x40, 0xf7, 0x1e, 0x05, 0x13, 0x59, 0x8a, 0xe9, 0x2f, 0x19, 0xe5, 0x02, 0x21, 0xa8, 0xa7,
	0x09, 0x13, 0x1d, 0xa7, 0x57, 0x3b, 0x7d, 0x82, 0xf5, 0x37, 0xfa, 0x16, 0x3e, 0xe3, 0x1a, 0x4b,
	0xb8, 0x02, 0x93, 0x69, 0x32, 0xa3, 0x9d, 0x9a, 0x04, 0xd4, 0xf1, 0x3e, 0x5f, 0x93, 0x5c, 0x48,
	0x33, 0xf2, 0xe0, 0xc0, 0x62, 0xa7, 0x19, 0x63, 0x34, 0x16, 0x44, 0x44, 0x2b, 0xda, 0xd9, 0xd1,
	0x68, 0x4b, 0x73, 0x61, 0x3c, 0x63, 0xe9, 0x40, 0x2f, 0xe1, 0x30, 0xe3, 0x94, 0x88, 0x45, 0xc4,
	0xc9, 0x22, 0xe1, 0x22, 0x0e, 0x57, 0x94, 0x44, 0xb1, 0x94, 0x1d, 0xce, 0x3a, 0xf5, 0x9e, 0x73,
	0xda, 0xc0, 0x5f, 0x48, 0xc0, 0x58, 0xfa, 0xaf, 0xad, 0xbb, 0x6f, 0xbc, 0x2e, 0x86, 0x2f, 0x4b,
	0x2f, 0xc2, 0xd3, 0x24, 0xe6, 0x14, 0x7d, 0x0f, 0xcd, 0x55, 0x98, 0x12, 0x99, 0x88, 0x45, 0x94,
	0xcb, 0x0b, 0xed, 0x9c, 0x36, 0xcf, 0x90, 0x97, 0x4e, 0xbc, 0xa1, 0x24, 0x09, 0xa4, 0x35, 0x9e,
	0x8f, 0xc2, 0x88, 0x61, 0x90, 0x30, 0xdf, 0xa0, 0xdc, 0x39, 0x1c, 0x6e, 0x72, 0x62, 0xaa, 0x0a,
	0x90, 0xd7, 0xe6, 0x39, 0xec, 0x9a, 0x0b, 0xe8, 0xea, 0x34, 0xcf, 0x5a, 0x8a, 0xcc, 0x00, 0x15,
	0x25, 0xb6, 0x5e, 0xe4, 0x42, 0x7d, 0x99, 0x48, 0xf9, 0x35, 0x29, 0xbf, 0x80, 0x1a, 0x48, 0x2b,
	0xd6, 0x3e, 0xf7, 0x59, 0xb1, 0x0b, 0x79, 0x22, 0xa3, 0xdd, 0x5d, 0x28, 0x19, 0xda, 0x12, 0x5c,
	0x85, 0x22, 0x5c, 0xfa, 0x8c, 0x25, 0xec, 0x63, 0x65, 0x9c, 0xc0, 0x13, 0xaa, 0xe2, 0xc8, 0x8a,
	0x72, 0x1e, 0xce, 0x4d, 0xcb, 0x1a, 0x78, 0x4f, 0x1b, 0xdf, 0x18, 0x9b, 0xd1, 0xb1, 0x9d, 0xc9,
	0xea, 0x38, 0x87, 0xe3, 0xd7, 0x54, 0x0c, 0x42, 0x2e, 0xae, 0xe4, 0x53, 0x5a, 0xd0, 0x59, 0xa0,
	0x34, 0xc4, 0x53, 0xda, 0x9f, 0xe5, 0x6a, 0x8e, 0xa1, 0xc9, 0xf4, 0x45, 0x88, 0xea, 0x8d, 0x96,
	0xb4, 0x87, 0xc1, 0x98, 0x94, 0x1c, 0xf7, 0x6f, 0x07, 0x7a, 0xd5, 0x24, 0xb6, 0x59, 0x3f, 0x40,
	0x67, 0x29, 0x01, 0xe4, 0xd6, 0x20, 0x08, 0xb7, 0x10, 0x12, 0xcd, 0x34, 0x65, 0x1d, 0x3f, 0x5d,
	0x96, 0x11, 0xa0, 0x9f, 0xe1, 0x88, 0x8b, 0x84, 0x51, 0x52, 0x19, 0x5e, 0xd3, 0x8d, 0x3f, 0xd0,
	0x45, 0x52, 0xc8, 0x8d, 0xec, 0x5d, 0x1d, 0x5a, 0xaa, 0xcc, 0xfd, 0x7d, 0x07, 0x9e, 0xda, 0x0e,
	0xc9, 0xf1, 0xa1, 0x63, 0x16, 0xc6, 0x3c, 0x12, 0xf2, 0x88, 0x7e, 0x82, 0x7d, 0x71, 0x77, 0x32,
	0xc3, 0xa0, 0x24, 0xb6, 0xce, 0x4e, 0x55, 0x8e, 0xd2, 0x18, 0x6f, 0xfd, 0xa9, 0xa6, 0x04, 0xb7,
	0x44, 0xe1, 0x8c, 0x5e, 0xdc, 0x15, 0x31, 0x8a, 0x6f, 0x13, 0x2b, 0xb9, 0xb5, 0xa6, 0xeb, 0x4b,
	0x6b, 0x5e, 0x54, 0xf5, 0x8d, 0x7a, 0xb0, 0x97, 0xa4, 0x34, 0x56, 0x17, 0x25, 0x71, 0xb6, 0x92,
	0xf3, 0xe5, 0xc8, 0x1a, 0x81, 0xb2, 0xc9, 0x3b, 0x0c, 0xb3, 0x95, 0xfb, 0x8f, 0x03, 0xad, 0x62,
	0x56, 0x04, 0xb0, 0x7b, 0x33, 0xf2, 0x87, 0xfe, 0x65, 0xfb, 0x13, 0xb4, 0x0f, 0xcd, 0xab, 0x57,
	0xfd, 0x81, 0x7f, 0x49, 0x94, 0xa9, 0xed, 0x28, 0xe7, 0xc5, 0xe0, 0x26, 0x90, 0xce, 0x9a, 0x5c,
	0x02, 0x2d, 0xec, 0xbf, 0xba, 0x7c, 0x4f, 0xc6, 0x37, 0x24, 0x18, 0x0d, 0xfa, 0xe3, 0xf6, 0x4e,
	0xc1, 0xf6, 0xc6, 0xc7, 0xaf, 0xfd, 0x76, 0x1d, 0xb5, 0x00, 0xb4, 0x9b, 0x8c, 0x6e, 0x86, 0xb8,
	0xfd, 0x48, 0x9d, 0xb5, 0xcb, 0x9c, 0x77, 0x51, 0x03, 0x1e, 0x99, 0xf0, 0x4f, 0x15, 0xbd, 0x76,
	0x5d, 0xb6, 0x1f, 0x2b, 0x2a, 0x13, 0x86, 0xfd, 0x77, 0x3e, 0x1e, 0x4b, 0x5b, 0x43, 0xd9, 0x4c,
	0xe8, 0x9d, 0x0d, 0xdc, 0x3f, 0x1c, 0x70, 0xf3, 0xc1, 0x28, 0x29, 0xea, 0xc7, 0xce, 0xc3, 0x4b,
	0x80, 0x75, 0xd9, 0x6d, 0x8d, 0x0f, 0x2b, 0x5b, 0x86, 0x37, 0xc0, 0xee, 0x8f, 0x70, 0xf2, 0xa0,
	0x10, 0xfb, 0x8a, 0xb7, 0x26, 0xce, 0xd1, 0x0b, 0xac, 0x38, 0x71, 0x13, 0x59, 0x48, 0xc3, 0x92,
	0x86, 0x53, 0xfa, 0x96, 0x6f, 0x75, 0xdf, 0x59, 0xaf, 0x8d, 0x8a, 0xee, 0xaf, 0x67, 0x8e, 0x47,
	0xbf, 0x51, 0xbd, 0x67, 0xea, 0x39, 0x20, 0x90, 0x16, 0x77, 0x78, 0xb7, 0x1a, 0x6d, 0x8e, 0xe2,
	0x22, 0x7b, 0x01, 0x0d, 0xae, 0x1c, 0x44, 0x6e, 0xd6, 0xcd, 0xc5, 0x78, 0x2f, 0xe6, 0x31, 0xb7,
	0x5f, 0xee, 0x11, 0x3c, 0x2b, 0xe7, 0x33, 0x17, 0x3f, 0xfb, 0xaf, 0x5e, 0xdc, 0x9b, 0xe6, 0x17,
	0x47, 0x7d, 0x47, 0x53, 0x8a, 0xde, 0xc1, 0x41, 0xc9, 0xa2, 0x46, 0x47, 0x1b, 0x29, 0x4b, 0x7e,
	0x8a, 0xba, 0xc7, 0x95, 0x7e, 0x5b, 0xee, 0x00, 0xd0, 0xf6, 0x0e, 0x45, 0x5f, 0xdd, 0x0f, 0x2b,
	0xdc, 0xbd, 0x7b, 0x54, 0xe5, 0xde, 0x24, 0xbd, 0xbf, 0x10, 0x73, 0xd2, 0x8a, 0x95, 0x9c, 0x93,
	0x56, 0xed, 0x51, 0x44, 0xa1, 0x53, 0xb5, 0x02, 0xd1, 0x89, 0x8a, 0xfd, 0xc0, 0x96, 0xed, 0x7e,
	0xfd, 0x30, 0xc8, 0xa6, 0x89, 0x55, 0xdb, 0x2b, 0x9f, 0x29, 0x7a, 0xbe, 0xa1, 0xf2, 0x81, 0x81,
	0xea, 0x7e, 0xf3, 0x41, 0x9c, 0xcd, 0xf7, 0x1e, 0x3e, 0x2f, 0xc0, 0xf2, 0x07, 0x7d, 0x5c, 0xf2,
	0x98, 0x0a, 0x4d, 0xe8, 0x55, 0x03, 0x0c, 0xf5, 0xf9, 0x5b, 0xf8, 0x2e, 0x61, 0x73, 0x2f, 0x94,
	0xde, 0x05, 0xf5, 0x16, 0xe1, 0x2c, 0x49, 0x52, 0x6f, 0x31, 0x51, 0x7f, 0x6e, 0xb8, 0x3c, 0xd1,
	0x99, 0xf9, 0x3b, 0x33, 0xc9, 0x6e, 0xbd, 0x39, 0x8d, 0x29, 0x93, 0x02, 0x67, 0xe7, 0x25, 0xff,
	0x8d, 0x46, 0x0a, 0xc5, 0xaf, 0x9d, 0x3f, 0x1d, 0xe7, 0x2f, 0xc7, 0xf9, 0x3f, 0x00, 0x00, 0xff,
	0xff, 0x08, 0xa1, 0x15, 0xcc, 0x3e, 0x09, 0x00, 0x00,
}
