// Code generated by protoc-gen-go.
// source: WAL.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ScopeType int32

const (
	ScopeType_REPLICATION_SCOPE_LOCAL  ScopeType = 0
	ScopeType_REPLICATION_SCOPE_GLOBAL ScopeType = 1
)

var ScopeType_name = map[int32]string{
	0: "REPLICATION_SCOPE_LOCAL",
	1: "REPLICATION_SCOPE_GLOBAL",
}
var ScopeType_value = map[string]int32{
	"REPLICATION_SCOPE_LOCAL":  0,
	"REPLICATION_SCOPE_GLOBAL": 1,
}

func (x ScopeType) Enum() *ScopeType {
	p := new(ScopeType)
	*p = x
	return p
}
func (x ScopeType) String() string {
	return proto.EnumName(ScopeType_name, int32(x))
}
func (x *ScopeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ScopeType_value, data, "ScopeType")
	if err != nil {
		return err
	}
	*x = ScopeType(value)
	return nil
}
func (ScopeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor30, []int{0} }

type FlushDescriptor_FlushAction int32

const (
	FlushDescriptor_START_FLUSH  FlushDescriptor_FlushAction = 0
	FlushDescriptor_COMMIT_FLUSH FlushDescriptor_FlushAction = 1
	FlushDescriptor_ABORT_FLUSH  FlushDescriptor_FlushAction = 2
	FlushDescriptor_CANNOT_FLUSH FlushDescriptor_FlushAction = 3
)

var FlushDescriptor_FlushAction_name = map[int32]string{
	0: "START_FLUSH",
	1: "COMMIT_FLUSH",
	2: "ABORT_FLUSH",
	3: "CANNOT_FLUSH",
}
var FlushDescriptor_FlushAction_value = map[string]int32{
	"START_FLUSH":  0,
	"COMMIT_FLUSH": 1,
	"ABORT_FLUSH":  2,
	"CANNOT_FLUSH": 3,
}

func (x FlushDescriptor_FlushAction) Enum() *FlushDescriptor_FlushAction {
	p := new(FlushDescriptor_FlushAction)
	*p = x
	return p
}
func (x FlushDescriptor_FlushAction) String() string {
	return proto.EnumName(FlushDescriptor_FlushAction_name, int32(x))
}
func (x *FlushDescriptor_FlushAction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FlushDescriptor_FlushAction_value, data, "FlushDescriptor_FlushAction")
	if err != nil {
		return err
	}
	*x = FlushDescriptor_FlushAction(value)
	return nil
}
func (FlushDescriptor_FlushAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor30, []int{4, 0}
}

type RegionEventDescriptor_EventType int32

const (
	RegionEventDescriptor_REGION_OPEN  RegionEventDescriptor_EventType = 0
	RegionEventDescriptor_REGION_CLOSE RegionEventDescriptor_EventType = 1
)

var RegionEventDescriptor_EventType_name = map[int32]string{
	0: "REGION_OPEN",
	1: "REGION_CLOSE",
}
var RegionEventDescriptor_EventType_value = map[string]int32{
	"REGION_OPEN":  0,
	"REGION_CLOSE": 1,
}

func (x RegionEventDescriptor_EventType) Enum() *RegionEventDescriptor_EventType {
	p := new(RegionEventDescriptor_EventType)
	*p = x
	return p
}
func (x RegionEventDescriptor_EventType) String() string {
	return proto.EnumName(RegionEventDescriptor_EventType_name, int32(x))
}
func (x *RegionEventDescriptor_EventType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegionEventDescriptor_EventType_value, data, "RegionEventDescriptor_EventType")
	if err != nil {
		return err
	}
	*x = RegionEventDescriptor_EventType(value)
	return nil
}
func (RegionEventDescriptor_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor30, []int{7, 0}
}

type WALHeader struct {
	HasCompression    *bool   `protobuf:"varint,1,opt,name=has_compression,json=hasCompression" json:"has_compression,omitempty"`
	EncryptionKey     []byte  `protobuf:"bytes,2,opt,name=encryption_key,json=encryptionKey" json:"encryption_key,omitempty"`
	HasTagCompression *bool   `protobuf:"varint,3,opt,name=has_tag_compression,json=hasTagCompression" json:"has_tag_compression,omitempty"`
	WriterClsName     *string `protobuf:"bytes,4,opt,name=writer_cls_name,json=writerClsName" json:"writer_cls_name,omitempty"`
	CellCodecClsName  *string `protobuf:"bytes,5,opt,name=cell_codec_cls_name,json=cellCodecClsName" json:"cell_codec_cls_name,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *WALHeader) Reset()                    { *m = WALHeader{} }
func (m *WALHeader) String() string            { return proto.CompactTextString(m) }
func (*WALHeader) ProtoMessage()               {}
func (*WALHeader) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{0} }

func (m *WALHeader) GetHasCompression() bool {
	if m != nil && m.HasCompression != nil {
		return *m.HasCompression
	}
	return false
}

func (m *WALHeader) GetEncryptionKey() []byte {
	if m != nil {
		return m.EncryptionKey
	}
	return nil
}

func (m *WALHeader) GetHasTagCompression() bool {
	if m != nil && m.HasTagCompression != nil {
		return *m.HasTagCompression
	}
	return false
}

func (m *WALHeader) GetWriterClsName() string {
	if m != nil && m.WriterClsName != nil {
		return *m.WriterClsName
	}
	return ""
}

func (m *WALHeader) GetCellCodecClsName() string {
	if m != nil && m.CellCodecClsName != nil {
		return *m.CellCodecClsName
	}
	return ""
}

//
// Protocol buffer version of WALKey; see WALKey comment, not really a key but WALEdit header
// for some KVs
type WALKey struct {
	EncodedRegionName []byte  `protobuf:"bytes,1,req,name=encoded_region_name,json=encodedRegionName" json:"encoded_region_name,omitempty"`
	TableName         []byte  `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	LogSequenceNumber *uint64 `protobuf:"varint,3,req,name=log_sequence_number,json=logSequenceNumber" json:"log_sequence_number,omitempty"`
	WriteTime         *uint64 `protobuf:"varint,4,req,name=write_time,json=writeTime" json:"write_time,omitempty"`
	//
	// This parameter is deprecated in favor of clusters which
	// contains the list of clusters that have consumed the change.
	// It is retained so that the log created by earlier releases (0.94)
	// can be read by the newer releases.
	ClusterId        *UUID          `protobuf:"bytes,5,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	Scopes           []*FamilyScope `protobuf:"bytes,6,rep,name=scopes" json:"scopes,omitempty"`
	FollowingKvCount *uint32        `protobuf:"varint,7,opt,name=following_kv_count,json=followingKvCount" json:"following_kv_count,omitempty"`
	//
	// This field contains the list of clusters that have
	// consumed the change
	ClusterIds         []*UUID `protobuf:"bytes,8,rep,name=cluster_ids,json=clusterIds" json:"cluster_ids,omitempty"`
	NonceGroup         *uint64 `protobuf:"varint,9,opt,name=nonceGroup" json:"nonceGroup,omitempty"`
	Nonce              *uint64 `protobuf:"varint,10,opt,name=nonce" json:"nonce,omitempty"`
	OrigSequenceNumber *uint64 `protobuf:"varint,11,opt,name=orig_sequence_number,json=origSequenceNumber" json:"orig_sequence_number,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (m *WALKey) Reset()                    { *m = WALKey{} }
func (m *WALKey) String() string            { return proto.CompactTextString(m) }
func (*WALKey) ProtoMessage()               {}
func (*WALKey) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{1} }

func (m *WALKey) GetEncodedRegionName() []byte {
	if m != nil {
		return m.EncodedRegionName
	}
	return nil
}

func (m *WALKey) GetTableName() []byte {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *WALKey) GetLogSequenceNumber() uint64 {
	if m != nil && m.LogSequenceNumber != nil {
		return *m.LogSequenceNumber
	}
	return 0
}

func (m *WALKey) GetWriteTime() uint64 {
	if m != nil && m.WriteTime != nil {
		return *m.WriteTime
	}
	return 0
}

func (m *WALKey) GetClusterId() *UUID {
	if m != nil {
		return m.ClusterId
	}
	return nil
}

func (m *WALKey) GetScopes() []*FamilyScope {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *WALKey) GetFollowingKvCount() uint32 {
	if m != nil && m.FollowingKvCount != nil {
		return *m.FollowingKvCount
	}
	return 0
}

func (m *WALKey) GetClusterIds() []*UUID {
	if m != nil {
		return m.ClusterIds
	}
	return nil
}

func (m *WALKey) GetNonceGroup() uint64 {
	if m != nil && m.NonceGroup != nil {
		return *m.NonceGroup
	}
	return 0
}

func (m *WALKey) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *WALKey) GetOrigSequenceNumber() uint64 {
	if m != nil && m.OrigSequenceNumber != nil {
		return *m.OrigSequenceNumber
	}
	return 0
}

type FamilyScope struct {
	Family           []byte     `protobuf:"bytes,1,req,name=family" json:"family,omitempty"`
	ScopeType        *ScopeType `protobuf:"varint,2,req,name=scope_type,json=scopeType,enum=pb.ScopeType" json:"scope_type,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *FamilyScope) Reset()                    { *m = FamilyScope{} }
func (m *FamilyScope) String() string            { return proto.CompactTextString(m) }
func (*FamilyScope) ProtoMessage()               {}
func (*FamilyScope) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{2} }

func (m *FamilyScope) GetFamily() []byte {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *FamilyScope) GetScopeType() ScopeType {
	if m != nil && m.ScopeType != nil {
		return *m.ScopeType
	}
	return ScopeType_REPLICATION_SCOPE_LOCAL
}

// *
// Special WAL entry to hold all related to a compaction.
// Written to WAL before completing compaction.  There is
// sufficient info in the below message to complete later
// the * compaction should we fail the WAL write.
type CompactionDescriptor struct {
	TableName         []byte   `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	EncodedRegionName []byte   `protobuf:"bytes,2,req,name=encoded_region_name,json=encodedRegionName" json:"encoded_region_name,omitempty"`
	FamilyName        []byte   `protobuf:"bytes,3,req,name=family_name,json=familyName" json:"family_name,omitempty"`
	CompactionInput   []string `protobuf:"bytes,4,rep,name=compaction_input,json=compactionInput" json:"compaction_input,omitempty"`
	CompactionOutput  []string `protobuf:"bytes,5,rep,name=compaction_output,json=compactionOutput" json:"compaction_output,omitempty"`
	StoreHomeDir      *string  `protobuf:"bytes,6,req,name=store_home_dir,json=storeHomeDir" json:"store_home_dir,omitempty"`
	RegionName        []byte   `protobuf:"bytes,7,opt,name=region_name,json=regionName" json:"region_name,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *CompactionDescriptor) Reset()                    { *m = CompactionDescriptor{} }
func (m *CompactionDescriptor) String() string            { return proto.CompactTextString(m) }
func (*CompactionDescriptor) ProtoMessage()               {}
func (*CompactionDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{3} }

func (m *CompactionDescriptor) GetTableName() []byte {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *CompactionDescriptor) GetEncodedRegionName() []byte {
	if m != nil {
		return m.EncodedRegionName
	}
	return nil
}

func (m *CompactionDescriptor) GetFamilyName() []byte {
	if m != nil {
		return m.FamilyName
	}
	return nil
}

func (m *CompactionDescriptor) GetCompactionInput() []string {
	if m != nil {
		return m.CompactionInput
	}
	return nil
}

func (m *CompactionDescriptor) GetCompactionOutput() []string {
	if m != nil {
		return m.CompactionOutput
	}
	return nil
}

func (m *CompactionDescriptor) GetStoreHomeDir() string {
	if m != nil && m.StoreHomeDir != nil {
		return *m.StoreHomeDir
	}
	return ""
}

func (m *CompactionDescriptor) GetRegionName() []byte {
	if m != nil {
		return m.RegionName
	}
	return nil
}

// *
// Special WAL entry to hold all related to a flush.
type FlushDescriptor struct {
	Action              *FlushDescriptor_FlushAction            `protobuf:"varint,1,req,name=action,enum=pb.FlushDescriptor_FlushAction" json:"action,omitempty"`
	TableName           []byte                                  `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	EncodedRegionName   []byte                                  `protobuf:"bytes,3,req,name=encoded_region_name,json=encodedRegionName" json:"encoded_region_name,omitempty"`
	FlushSequenceNumber *uint64                                 `protobuf:"varint,4,opt,name=flush_sequence_number,json=flushSequenceNumber" json:"flush_sequence_number,omitempty"`
	StoreFlushes        []*FlushDescriptor_StoreFlushDescriptor `protobuf:"bytes,5,rep,name=store_flushes,json=storeFlushes" json:"store_flushes,omitempty"`
	RegionName          []byte                                  `protobuf:"bytes,6,opt,name=region_name,json=regionName" json:"region_name,omitempty"`
	XXX_unrecognized    []byte                                  `json:"-"`
}

func (m *FlushDescriptor) Reset()                    { *m = FlushDescriptor{} }
func (m *FlushDescriptor) String() string            { return proto.CompactTextString(m) }
func (*FlushDescriptor) ProtoMessage()               {}
func (*FlushDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{4} }

func (m *FlushDescriptor) GetAction() FlushDescriptor_FlushAction {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return FlushDescriptor_START_FLUSH
}

func (m *FlushDescriptor) GetTableName() []byte {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *FlushDescriptor) GetEncodedRegionName() []byte {
	if m != nil {
		return m.EncodedRegionName
	}
	return nil
}

func (m *FlushDescriptor) GetFlushSequenceNumber() uint64 {
	if m != nil && m.FlushSequenceNumber != nil {
		return *m.FlushSequenceNumber
	}
	return 0
}

func (m *FlushDescriptor) GetStoreFlushes() []*FlushDescriptor_StoreFlushDescriptor {
	if m != nil {
		return m.StoreFlushes
	}
	return nil
}

func (m *FlushDescriptor) GetRegionName() []byte {
	if m != nil {
		return m.RegionName
	}
	return nil
}

type FlushDescriptor_StoreFlushDescriptor struct {
	FamilyName       []byte   `protobuf:"bytes,1,req,name=family_name,json=familyName" json:"family_name,omitempty"`
	StoreHomeDir     *string  `protobuf:"bytes,2,req,name=store_home_dir,json=storeHomeDir" json:"store_home_dir,omitempty"`
	FlushOutput      []string `protobuf:"bytes,3,rep,name=flush_output,json=flushOutput" json:"flush_output,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FlushDescriptor_StoreFlushDescriptor) Reset()         { *m = FlushDescriptor_StoreFlushDescriptor{} }
func (m *FlushDescriptor_StoreFlushDescriptor) String() string { return proto.CompactTextString(m) }
func (*FlushDescriptor_StoreFlushDescriptor) ProtoMessage()    {}
func (*FlushDescriptor_StoreFlushDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor30, []int{4, 0}
}

func (m *FlushDescriptor_StoreFlushDescriptor) GetFamilyName() []byte {
	if m != nil {
		return m.FamilyName
	}
	return nil
}

func (m *FlushDescriptor_StoreFlushDescriptor) GetStoreHomeDir() string {
	if m != nil && m.StoreHomeDir != nil {
		return *m.StoreHomeDir
	}
	return ""
}

func (m *FlushDescriptor_StoreFlushDescriptor) GetFlushOutput() []string {
	if m != nil {
		return m.FlushOutput
	}
	return nil
}

type StoreDescriptor struct {
	FamilyName       []byte   `protobuf:"bytes,1,req,name=family_name,json=familyName" json:"family_name,omitempty"`
	StoreHomeDir     *string  `protobuf:"bytes,2,req,name=store_home_dir,json=storeHomeDir" json:"store_home_dir,omitempty"`
	StoreFile        []string `protobuf:"bytes,3,rep,name=store_file,json=storeFile" json:"store_file,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *StoreDescriptor) Reset()                    { *m = StoreDescriptor{} }
func (m *StoreDescriptor) String() string            { return proto.CompactTextString(m) }
func (*StoreDescriptor) ProtoMessage()               {}
func (*StoreDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{5} }

func (m *StoreDescriptor) GetFamilyName() []byte {
	if m != nil {
		return m.FamilyName
	}
	return nil
}

func (m *StoreDescriptor) GetStoreHomeDir() string {
	if m != nil && m.StoreHomeDir != nil {
		return *m.StoreHomeDir
	}
	return ""
}

func (m *StoreDescriptor) GetStoreFile() []string {
	if m != nil {
		return m.StoreFile
	}
	return nil
}

// *
// Special WAL entry used for writing bulk load events to WAL
type BulkLoadDescriptor struct {
	TableName         *TableName         `protobuf:"bytes,1,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	EncodedRegionName []byte             `protobuf:"bytes,2,req,name=encoded_region_name,json=encodedRegionName" json:"encoded_region_name,omitempty"`
	Stores            []*StoreDescriptor `protobuf:"bytes,3,rep,name=stores" json:"stores,omitempty"`
	BulkloadSeqNum    *int64             `protobuf:"varint,4,req,name=bulkload_seq_num,json=bulkloadSeqNum" json:"bulkload_seq_num,omitempty"`
	XXX_unrecognized  []byte             `json:"-"`
}

func (m *BulkLoadDescriptor) Reset()                    { *m = BulkLoadDescriptor{} }
func (m *BulkLoadDescriptor) String() string            { return proto.CompactTextString(m) }
func (*BulkLoadDescriptor) ProtoMessage()               {}
func (*BulkLoadDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{6} }

func (m *BulkLoadDescriptor) GetTableName() *TableName {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *BulkLoadDescriptor) GetEncodedRegionName() []byte {
	if m != nil {
		return m.EncodedRegionName
	}
	return nil
}

func (m *BulkLoadDescriptor) GetStores() []*StoreDescriptor {
	if m != nil {
		return m.Stores
	}
	return nil
}

func (m *BulkLoadDescriptor) GetBulkloadSeqNum() int64 {
	if m != nil && m.BulkloadSeqNum != nil {
		return *m.BulkloadSeqNum
	}
	return 0
}

// *
// Special WAL entry to hold all related to a region event (open/close).
type RegionEventDescriptor struct {
	EventType         *RegionEventDescriptor_EventType `protobuf:"varint,1,req,name=event_type,json=eventType,enum=pb.RegionEventDescriptor_EventType" json:"event_type,omitempty"`
	TableName         []byte                           `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	EncodedRegionName []byte                           `protobuf:"bytes,3,req,name=encoded_region_name,json=encodedRegionName" json:"encoded_region_name,omitempty"`
	LogSequenceNumber *uint64                          `protobuf:"varint,4,opt,name=log_sequence_number,json=logSequenceNumber" json:"log_sequence_number,omitempty"`
	Stores            []*StoreDescriptor               `protobuf:"bytes,5,rep,name=stores" json:"stores,omitempty"`
	Server            *ServerName                      `protobuf:"bytes,6,opt,name=server" json:"server,omitempty"`
	RegionName        []byte                           `protobuf:"bytes,7,opt,name=region_name,json=regionName" json:"region_name,omitempty"`
	XXX_unrecognized  []byte                           `json:"-"`
}

func (m *RegionEventDescriptor) Reset()                    { *m = RegionEventDescriptor{} }
func (m *RegionEventDescriptor) String() string            { return proto.CompactTextString(m) }
func (*RegionEventDescriptor) ProtoMessage()               {}
func (*RegionEventDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{7} }

func (m *RegionEventDescriptor) GetEventType() RegionEventDescriptor_EventType {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return RegionEventDescriptor_REGION_OPEN
}

func (m *RegionEventDescriptor) GetTableName() []byte {
	if m != nil {
		return m.TableName
	}
	return nil
}

func (m *RegionEventDescriptor) GetEncodedRegionName() []byte {
	if m != nil {
		return m.EncodedRegionName
	}
	return nil
}

func (m *RegionEventDescriptor) GetLogSequenceNumber() uint64 {
	if m != nil && m.LogSequenceNumber != nil {
		return *m.LogSequenceNumber
	}
	return 0
}

func (m *RegionEventDescriptor) GetStores() []*StoreDescriptor {
	if m != nil {
		return m.Stores
	}
	return nil
}

func (m *RegionEventDescriptor) GetServer() *ServerName {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *RegionEventDescriptor) GetRegionName() []byte {
	if m != nil {
		return m.RegionName
	}
	return nil
}

// *
// A trailer that is appended to the end of a properly closed WAL file.
// If missing, this is either a legacy or a corrupted WAL file.
// N.B. This trailer currently doesn't contain any information and we
// purposefully don't expose it in the WAL APIs. It's for future growth.
type WALTrailer struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *WALTrailer) Reset()                    { *m = WALTrailer{} }
func (m *WALTrailer) String() string            { return proto.CompactTextString(m) }
func (*WALTrailer) ProtoMessage()               {}
func (*WALTrailer) Descriptor() ([]byte, []int) { return fileDescriptor30, []int{8} }

func init() {
	proto.RegisterType((*WALHeader)(nil), "pb.WALHeader")
	proto.RegisterType((*WALKey)(nil), "pb.WALKey")
	proto.RegisterType((*FamilyScope)(nil), "pb.FamilyScope")
	proto.RegisterType((*CompactionDescriptor)(nil), "pb.CompactionDescriptor")
	proto.RegisterType((*FlushDescriptor)(nil), "pb.FlushDescriptor")
	proto.RegisterType((*FlushDescriptor_StoreFlushDescriptor)(nil), "pb.FlushDescriptor.StoreFlushDescriptor")
	proto.RegisterType((*StoreDescriptor)(nil), "pb.StoreDescriptor")
	proto.RegisterType((*BulkLoadDescriptor)(nil), "pb.BulkLoadDescriptor")
	proto.RegisterType((*RegionEventDescriptor)(nil), "pb.RegionEventDescriptor")
	proto.RegisterType((*WALTrailer)(nil), "pb.WALTrailer")
	proto.RegisterEnum("pb.ScopeType", ScopeType_name, ScopeType_value)
	proto.RegisterEnum("pb.FlushDescriptor_FlushAction", FlushDescriptor_FlushAction_name, FlushDescriptor_FlushAction_value)
	proto.RegisterEnum("pb.RegionEventDescriptor_EventType", RegionEventDescriptor_EventType_name, RegionEventDescriptor_EventType_value)
}

var fileDescriptor30 = []byte{
	// 1054 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xcb, 0x72, 0xe2, 0x46,
	0x17, 0x1e, 0x09, 0x9b, 0x31, 0x47, 0x18, 0x70, 0xdb, 0xf3, 0xff, 0x2a, 0xe7, 0x32, 0x0e, 0x49,
	0x26, 0x9e, 0x4b, 0x54, 0x29, 0x36, 0x59, 0xa6, 0x40, 0xbe, 0x51, 0x83, 0xc1, 0x25, 0x70, 0x65,
	0xa9, 0x12, 0xa2, 0x0d, 0x2a, 0xcb, 0x48, 0x69, 0x09, 0xbb, 0xd8, 0xcd, 0x32, 0x2f, 0x90, 0x7d,
	0x36, 0x79, 0x8c, 0x3c, 0x40, 0x5e, 0x23, 0x4f, 0x92, 0xd3, 0xa7, 0xc5, 0xc5, 0x80, 0x6b, 0x52,
	0x95, 0xd9, 0xd1, 0xdf, 0xf7, 0xe9, 0xe8, 0x5c, 0xbe, 0xd3, 0x02, 0x0a, 0x3f, 0xd7, 0x5b, 0x56,
	0x2c, 0xa2, 0x34, 0x62, 0x7a, 0xdc, 0x3f, 0x34, 0x2e, 0x1a, 0x5e, 0xc2, 0x15, 0x70, 0x58, 0xb4,
	0xc3, 0x80, 0x8f, 0x53, 0x75, 0xaa, 0xfe, 0xad, 0x91, 0xf8, 0x82, 0x7b, 0x03, 0x2e, 0xd8, 0x77,
	0x50, 0x1e, 0x79, 0x89, 0xeb, 0x47, 0x77, 0xb1, 0xe0, 0x49, 0x12, 0x44, 0x63, 0x53, 0x3b, 0xd2,
	0x8e, 0x77, 0x9c, 0x12, 0xc2, 0xf6, 0x02, 0x65, 0xdf, 0x42, 0x89, 0x8f, 0x7d, 0x31, 0x8d, 0x53,
	0x3c, 0xb9, 0xb7, 0x7c, 0x6a, 0xea, 0xa8, 0x2b, 0x3a, 0xbb, 0x0b, 0xf4, 0x3d, 0x9f, 0x32, 0x0b,
	0xf6, 0x65, 0xbc, 0xd4, 0x1b, 0x3e, 0x8a, 0x99, 0xa3, 0x98, 0x7b, 0x48, 0xf5, 0xbc, 0xe1, 0x72,
	0xd8, 0x57, 0x50, 0x7e, 0x10, 0x41, 0xca, 0x85, 0xeb, 0x87, 0x89, 0x3b, 0xf6, 0xee, 0xb8, 0xb9,
	0x85, 0xda, 0x82, 0xb3, 0xab, 0x60, 0x3b, 0x4c, 0xda, 0x08, 0xb2, 0xef, 0x61, 0xdf, 0xe7, 0x61,
	0x88, 0x41, 0x07, 0xdc, 0x5f, 0x68, 0xb7, 0x49, 0x5b, 0x91, 0x94, 0x2d, 0x99, 0x4c, 0x5e, 0xfd,
	0x33, 0x07, 0x79, 0x2c, 0x32, 0xcb, 0x08, 0x53, 0x44, 0x72, 0xe0, 0x0a, 0x3e, 0x94, 0xc9, 0xd3,
	0x93, 0xda, 0x91, 0x8e, 0xd9, 0xef, 0x65, 0x94, 0x43, 0x0c, 0xbd, 0xe9, 0x0b, 0x80, 0xd4, 0xeb,
	0x87, 0x5c, 0xc9, 0x74, 0x92, 0x15, 0x08, 0x21, 0x1a, 0xc3, 0x85, 0xd1, 0xd0, 0x4d, 0xf8, 0x2f,
	0x13, 0x7c, 0x16, 0x55, 0x93, 0xbb, 0x3e, 0x17, 0x58, 0xa0, 0x7e, 0xbc, 0xe5, 0xec, 0x21, 0xd5,
	0xcd, 0x98, 0x36, 0x11, 0x32, 0x1c, 0x55, 0xe2, 0xa6, 0x01, 0xd5, 0x26, 0x65, 0x05, 0x42, 0x7a,
	0x08, 0xb0, 0xb7, 0x00, 0x7e, 0x38, 0x49, 0x64, 0x03, 0x82, 0x01, 0x95, 0x63, 0xd4, 0x76, 0xac,
	0xb8, 0x6f, 0x5d, 0x5f, 0x37, 0x4f, 0x1a, 0xba, 0xa9, 0x39, 0x85, 0x8c, 0x6f, 0x0e, 0x70, 0x58,
	0xf9, 0xc4, 0x8f, 0x62, 0x9e, 0x98, 0xf9, 0xa3, 0x1c, 0x0a, 0xcb, 0x52, 0x78, 0xe6, 0xdd, 0x05,
	0xe1, 0xb4, 0x2b, 0x71, 0x27, 0xa3, 0xd9, 0x3b, 0x60, 0x37, 0x51, 0x18, 0x46, 0x0f, 0xc1, 0x78,
	0xe8, 0xde, 0xde, 0x63, 0xd7, 0x26, 0xe3, 0xd4, 0x7c, 0x8e, 0xd1, 0x77, 0x9d, 0xca, 0x9c, 0x79,
	0x7f, 0x6f, 0x4b, 0x9c, 0xbd, 0x06, 0x63, 0x91, 0x43, 0x62, 0xee, 0x50, 0xec, 0x79, 0x12, 0x0e,
	0xcc, 0x13, 0x48, 0xd8, 0x97, 0x00, 0xe3, 0x08, 0x8b, 0x3b, 0x17, 0xd1, 0x24, 0x36, 0x0b, 0x18,
	0x70, 0xcb, 0x59, 0x42, 0xd8, 0x01, 0x6c, 0xd3, 0xc9, 0x04, 0xa2, 0xd4, 0x81, 0xfd, 0x00, 0x07,
	0x91, 0x08, 0xd6, 0x9b, 0x66, 0x90, 0x88, 0x49, 0xee, 0x71, 0xd7, 0xaa, 0x5d, 0x30, 0x96, 0xea,
	0x62, 0xff, 0x83, 0xfc, 0x0d, 0x1d, 0xb3, 0xb1, 0x65, 0x27, 0xac, 0x13, 0xa8, 0x62, 0x37, 0x9d,
	0xc6, 0x6a, 0x56, 0xa5, 0xda, 0xae, 0x4c, 0x9c, 0x1e, 0xeb, 0x21, 0xe8, 0x14, 0x92, 0xd9, 0xcf,
	0xea, 0x1f, 0x3a, 0x1c, 0x48, 0xef, 0x79, 0xbe, 0x74, 0xeb, 0x09, 0x4f, 0x7c, 0x11, 0xc4, 0x69,
	0x24, 0x56, 0x46, 0xae, 0x6d, 0x18, 0xf9, 0x26, 0x07, 0xe9, 0x4f, 0x39, 0xe8, 0x25, 0x18, 0x2a,
	0x3f, 0xa5, 0xcb, 0x91, 0x0e, 0x14, 0x44, 0x82, 0xd7, 0x50, 0xf1, 0xe7, 0x79, 0xb8, 0xc1, 0x38,
	0x9e, 0xa4, 0xe8, 0x8c, 0x1c, 0x3a, 0xb9, 0xbc, 0xc0, 0x9b, 0x12, 0x46, 0x7f, 0xec, 0x2d, 0x49,
	0xa3, 0x49, 0x2a, 0xb5, 0xdb, 0xa4, 0x5d, 0x8a, 0xd1, 0x21, 0x9c, 0x7d, 0x03, 0xa5, 0x04, 0xeb,
	0xe1, 0xee, 0x28, 0xba, 0xe3, 0xee, 0x20, 0x10, 0xe8, 0x13, 0x1d, 0x95, 0x45, 0x42, 0x2f, 0x10,
	0x3c, 0x09, 0x84, 0x4c, 0x6f, 0xb9, 0x8c, 0xe7, 0xb4, 0xc6, 0x20, 0xe6, 0xf9, 0x57, 0x7f, 0xdb,
	0x82, 0xf2, 0x19, 0xce, 0x7c, 0xb4, 0xd4, 0xa2, 0x1f, 0x21, 0xaf, 0x5e, 0x45, 0xed, 0x29, 0xd5,
	0x5e, 0x92, 0xf5, 0x1e, 0x8b, 0xd4, 0xb9, 0x4e, 0x32, 0x27, 0x93, 0xff, 0x8b, 0x75, 0xda, 0xd4,
	0xdb, 0xdc, 0x53, 0xbd, 0xad, 0xc1, 0x8b, 0x1b, 0xf9, 0x96, 0x35, 0x2f, 0x6d, 0x91, 0x97, 0xf6,
	0x89, 0x5c, 0x59, 0xc1, 0x4b, 0xd8, 0x55, 0x6d, 0x21, 0x12, 0xb7, 0x67, 0x9b, 0x1c, 0x7e, 0xbc,
	0xa9, 0x84, 0xae, 0x14, 0xae, 0x80, 0x59, 0xff, 0xce, 0xd4, 0xd3, 0xab, 0xfd, 0xcb, 0xaf, 0xf6,
	0xef, 0xf0, 0x83, 0x06, 0x07, 0x9b, 0xe2, 0xac, 0x1a, 0x43, 0x5b, 0x33, 0xc6, 0xfa, 0x00, 0xf5,
	0x0d, 0x03, 0xfc, 0x0a, 0x8a, 0xaa, 0x07, 0x99, 0x1d, 0x72, 0x64, 0x07, 0x83, 0x30, 0xe5, 0x04,
	0xda, 0x9f, 0xc5, 0x30, 0x58, 0x19, 0x8c, 0x6e, 0xaf, 0xee, 0xf4, 0xdc, 0xb3, 0xd6, 0x75, 0xf7,
	0xa2, 0xf2, 0x8c, 0x55, 0xa0, 0x68, 0x77, 0x2e, 0x2f, 0x9b, 0x33, 0x44, 0x93, 0x92, 0x7a, 0xa3,
	0x33, 0x97, 0xe8, 0x24, 0xa9, 0xb7, 0xdb, 0x9d, 0x19, 0x92, 0xab, 0x3e, 0x40, 0x99, 0xca, 0xfa,
	0xf4, 0x15, 0xa1, 0x49, 0xb2, 0x09, 0x05, 0x21, 0xcf, 0xea, 0x29, 0xa8, 0xa6, 0x23, 0x50, 0xfd,
	0x4b, 0x03, 0xd6, 0x98, 0x84, 0xb7, 0xad, 0xc8, 0x1b, 0x2c, 0xbd, 0xfc, 0xdd, 0xda, 0xda, 0x1a,
	0x6a, 0xfb, 0x7b, 0x33, 0x7b, 0xfd, 0x97, 0x2d, 0x7e, 0x8b, 0x97, 0xad, 0xcc, 0x20, 0xa1, 0x7c,
	0x8c, 0xda, 0x3e, 0xdd, 0x2b, 0x8f, 0xeb, 0x77, 0x32, 0x09, 0x3b, 0x86, 0x4a, 0x1f, 0x13, 0x0c,
	0x31, 0x41, 0xe9, 0x4c, 0x69, 0x4a, 0xba, 0xeb, 0x73, 0x4e, 0x69, 0x86, 0xa3, 0x29, 0xd1, 0x8f,
	0xd5, 0x0f, 0x39, 0x78, 0xa1, 0xde, 0x72, 0x7a, 0x8f, 0x1f, 0xe5, 0xa5, 0x72, 0x1a, 0x00, 0x5c,
	0x42, 0xea, 0x32, 0x53, 0x6b, 0xf6, 0xb5, 0x7c, 0xe9, 0x46, 0xb9, 0x45, 0x67, 0x75, 0xc5, 0xf1,
	0xd9, 0xcf, 0x4f, 0xbd, 0x6d, 0x4f, 0x7c, 0xec, 0xd4, 0xae, 0x6d, 0xf8, 0xd8, 0x2d, 0x7a, 0xb6,
	0xfd, 0xf1, 0x9e, 0xbd, 0x42, 0x31, 0x17, 0xf7, 0x5c, 0xd0, 0x0a, 0x19, 0xb5, 0x12, 0x89, 0x09,
	0xa1, 0xd9, 0x65, 0xec, 0xc7, 0xef, 0x2b, 0x0b, 0x0a, 0xf3, 0x66, 0x48, 0x1f, 0x3b, 0xa7, 0xe7,
	0xcd, 0x4e, 0xdb, 0xed, 0x5c, 0x9d, 0xb6, 0x95, 0xd5, 0x33, 0xc0, 0x6e, 0x75, 0xba, 0xa7, 0x15,
	0xad, 0x5a, 0x04, 0xc0, 0xff, 0x06, 0x3d, 0xe1, 0xa1, 0xb7, 0xc4, 0x9b, 0x33, 0x28, 0xcc, 0xbf,
	0x16, 0xec, 0x33, 0xf8, 0xbf, 0x73, 0x7a, 0xd5, 0x6a, 0xda, 0xf5, 0x9e, 0x7c, 0xa2, 0x6b, 0x63,
	0x10, 0xb7, 0xd5, 0xb1, 0xeb, 0x2d, 0x8c, 0xf4, 0x39, 0x98, 0xeb, 0xe4, 0x79, 0xab, 0xd3, 0x40,
	0x56, 0x6b, 0xfc, 0x04, 0x6f, 0x22, 0x31, 0xb4, 0x3c, 0xbc, 0x92, 0x47, 0xdc, 0x1a, 0x79, 0x83,
	0x28, 0x8a, 0xad, 0x51, 0x7f, 0xfe, 0x37, 0xac, 0x3f, 0xb9, 0xb1, 0x86, 0x7c, 0xcc, 0x85, 0x97,
	0xf2, 0x41, 0x43, 0xfe, 0x05, 0xbb, 0x92, 0x70, 0x72, 0xa1, 0xfd, 0xaa, 0x3d, 0xfb, 0x5d, 0xd3,
	0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x12, 0x93, 0xdf, 0xf5, 0xc3, 0x09, 0x00, 0x00,
}
